### PR TITLE
Bug 1889701: Use openshift/api as the source of truth for CNO CRD

### PR DESCRIPTION
**Pull request by rcarrillocruz**

### CODE REVIEW

**Comment by squeed** [comment]
Much easier, thanks!
/lgtm

**Comment by squeed** [comment]
actually, hang on. Do we even need this file at all, or is it created somewhere else?
/lgtm cancel

**Comment by rcarrillocruz** [comment]
I see quite a bit of discrepancies between the CRD on openshift/api vs CNO. I think I'll push a copy straight to openshift/api first, looks like the CI issues may be due to some issues with the fields

**Comment by rcarrillocruz** [comment]
We need to wait for https://github.com/openshift/api/pull/770/files to land, otherwise we'll keep getting the oc explain test failure.

**Comment by rcarrillocruz** [comment]
Closing as https://github.com/openshift/cluster-network-operator/pull/863 implements this

**Pull request closed without merging**
