### PR TITLE
Bug 2100079: Update sdn-controller perms for "configmapsleases" leaderelection

### PR DESCRIPTION
**Pull request by danwinship**
needed for 1.24 rebase (https://github.com/openshift/sdn/pull/440)

### CODE REVIEW

**Comment by kyrtapz** [comment]
/retitle Bug 2100079: Update sdn-controller perms for "configmapsleases" leaderelection #

**Comment by danwinship** [comment]
/override ci/prow/e2e-network-migration
job is mostly broken and is blocking this from merging, which is blocking another PR from merging which is blocking another PR from merging

**Pull request merged**
