### PR TITLE
CCO-356: Add Infrastructures permission to CNCC cluster role

### PR DESCRIPTION
**Pull request by dlom**
Necessary for https://github.com/openshift/cloud-network-config-controller/pull/102 to access the cluster infrastructure object

/assign @kyrtapz 
/cc @jcaamano

### CODE REVIEW

**Comment by jcaamano** [comment]
overriding e2e-aws-ovn-network-migration
https://issues.redhat.com/browse/OCPBUGS-15287

/override ci/prow/e2e-aws-ovn-network-migration
/approve

**Comment by kyrtapz** [comment]
e2e-gcp-ovn is not doing great but the failures are not consistent and don't seem to be related to this pr
/retest-required

**Pull request merged**
