### PR TITLE
Revert "Merge pull request #2037 from dcbw/db-script-cleanup"

### PR DESCRIPTION
**Pull request by dgoodwin**
This reverts commit bc998c548265962d7ce6d518b5177c3ade16d77c, reversing changes made to 504e5913a525a7d337568a89cfa2a63eb2ddc693.

Change was full failing on ovn cluster upgrades, See [TRT-1292](https://issues.redhat.com//browse/TRT-1292) for details.

### CODE REVIEW

**Comment by dulek** [comment]
@dgoodwin: Does it have anything to do with the commit removing Kuryr or is it just the wrong hash in the description?

**Comment by dgoodwin** [comment]
@dulek I think it implies the Kuryr commit was the previous head when it says "changes to".

**Pull request merged**
