### PR TITLE
add more sysctls to the multus allowlist

### PR DESCRIPTION
**Pull request by yuvalk**
- Extend the tuning cni sysctl allowlist
- add rules on cni safe sysctls list

### CODE REVIEW

**Comment by yuvalk** [comment]
this is cont of https://github.com/openshift/cluster-network-operator/commit/70f18a9a64302b41dd7027f818b8ce385479ead9
with just some more sysctls that were deemed safe

**Comment by mmirecki** [comment]
lgtm

**Comment by zshi-redhat** [comment]
@yuvalk just curious, who consumes the allowlist, is it tuning CNI (I didn't see it reads the allowlist)?

**Pull request merged**
