### PR TITLE
Bumps openshift/api to consume config.proxy.readinessendpoints

### PR DESCRIPTION
**Pull request by danehans**
Dep bump needed to consume `ReadinessEndpoints` from `Proxy` type for future proxy reconciliation. Required by https://github.com/openshift/cluster-network-operator/pull/245

@squeed @openshift/networking PTAL

### CODE REVIEW

**Comment by squeed** [comment]
Looks like that API bump needs a bit of type renaming in the operator code.

**Comment by danehans** [comment]
@squeed I pushed a new commit this morning to handle the renaming.

**Comment by squeed** [comment]
Looks like this is also covered in #250

**Comment by danwinship** [comment]
yeah, #250 did this and is now merged

**Comment by danehans** [comment]
PR ships in the night ;-) Closing due to https://github.com/openshift/cluster-network-operator/pull/250

**Pull request closed without merging**
