### PR TITLE
[release-4.13] HOSTEDCP-967: Updated Hypershift API version to v1beta1

### PR DESCRIPTION
**Pull request by muraee**
This is needed since we are dropping `v1alpha1` dropped here https://github.com/openshift/hypershift/pull/2562 and our upgrade test depends on 4.13

### CODE REVIEW

**Comment by csrwng** [comment]
/lgtm
@kyrtapz ptal

**Comment by kyrtapz** [comment]
This is included in https://github.com/openshift/cluster-network-operator/pull/1802
@muraee can we close this PR and wait for https://github.com/openshift/cluster-network-operator/pull/1802 to merge?

**Comment by muraee** [comment]
/close
changes already included in https://github.com/openshift/cluster-network-operator/pull/1802

**Comment by kyrtapz** [comment]
@muraee there is already a PR open that includes the bump: https://github.com/openshift/cluster-network-operator/pull/1816

**Pull request closed without merging**
