### PR TITLE
Bug 1939752: ovnkube: add missing resource requests for SBDB

### PR DESCRIPTION
**Pull request by dcbw**
@smarterclayton @trozet

### CODE REVIEW

**Comment by smarterclayton** [comment]
lgtm

**Comment by aojea** [comment]
/lgtm
This.is consistent with the nbdb and the master,

**Comment by dcbw** [comment]
/override ci/prow/e2e-agnostic-upgrade
because https://bugzilla.redhat.com/show_bug.cgi?id=1933760 is killing that job

**Pull request merged**
