### PR TITLE
Fix MTU detection for multi path default routes

### PR DESCRIPTION
**Pull request by kyrtapz**
Multi path routes do not have a link index attribute set on the route, instead each path has it's own link index.

Signed-off-by: Patryk Diak <pdiak@redhat.com>

### CODE REVIEW

**Comment by squeed** [comment]
Seems reasonable. While we're in here touching this code, how about we add a fallback mode that picks the first up non-veth with a L3 address?

**Comment by kyrtapz** [comment]
> Seems reasonable. While we're in here touching this code, how about we add a fallback mode that picks the first up non-veth with a L3 address?

Don't we have a requirement that the default route is defined?
For ovn-k we check it in `configure-ovs` https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/configure-ovs-network.yaml#L510

**Comment by kyrtapz** [comment]
@jcaamano PTAL

**Comment by squeed** [comment]
> Don't we have a requirement that the default route has to be defined?

Sure. Was just thinking of extra paranoia to keep the progress moving forward
/approve
/lgtm
/retest-required

**Pull request merged**
