### PR TITLE
Remove Kuryr mutating DNS webhook

### PR DESCRIPTION
**Pull request by dulek**
This mutating webhook was a hack to allow running OpenShift with Kuryr
on older OpenStack versions that were not supporting specifying multiple
listeners for an Octavia LB. This meant that the DNS LB was only
listening for TCP requests and all of the pods got to have the DNS
options in the spec adjusted for that. The webhook injected them.

Obviously a terrible thing, but so is running old OpenStack. Anyway
4.10 (or even 4.9?) dropped support for OSP13, meaning that all the
Octavia versions we'll run against will support multiple listeners in an
LB and this dangerous hack can be rightfully removed.

### CODE REVIEW

**Comment by dulek** [comment]
/hold

I'd like to wait for a confirmation from @MaysaMacedo that this is sane.

**Comment by dulek** [comment]
/hold cancel

CI is fine now.

**Comment by squeed** [comment]
/override ci/prow/e2e-aws-sdn-multi
clearly unrelated...

**Pull request merged**
