### PR TITLE
OCPBUGS-15961: FIPS related CNO changes

### PR DESCRIPTION
**Pull request by abhat**
Add logic to pick CNI shim binaries for ovn-k and sdn based on the host os version.

### CODE REVIEW

**Comment by dougbtv** [comment]
I compared this against

https://github.com/openshift/cluster-network-operator/pull/1880
https://github.com/openshift/cluster-network-operator/pull/1877

Which this appears to be a combination of. Looks like a match to me

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

image registry pull failures

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-ovn-windows

level=fatal msg=failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get vsphere Terraform variables: failed to use cached vsphere image: Checksum mismatch for /tmp/.cache/openshift-installer/image_cache/rhcos-414.92.202307070025-0-vmware.x86_64.ova; expected=101330e9bdb6eb1730d1684a71cc00ada0b6ccf6a60eaa7223b6d5a3f2c49365 found=8eda4ada9c7d568a129bfb914a86cf7260e363a508ef1b5aa951db80dad7a001

**Pull request merged**
