### PR TITLE
OCPBUGS-23729: Set replicas of Multus admission controller according to Hypershift ControllerAvailabilityPolicy

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by pliurh** [comment]
@enxebre PTAL

**Comment by pliurh** [comment]
@zshi-redhat PTAL

**Comment by kyrtapz** [comment]
/lgtm

This is the same approach we use for ovn-k:
https://github.com/openshift/cluster-network-operator/blob/f5757f9eabd0a109ed331a4663dc29ea38742e80/pkg/network/node_identity.go#L87-L90

**Pull request merged**
