### PR TITLE
Fix Watch arguments in configmap operator

### PR DESCRIPTION
**Pull request by s1061123**
EnqueueRequestForOwner{} will enqueue the owner of the target,
hence it enqueue configmap owner, network CR. This change fixes
reconciler function to match it.

### CODE REVIEW

**Comment by dougbtv** [comment]
Related to this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1731392

**Comment by squeed** [comment]
Interesting! Apparently EnqueueRequestForOwner doesn't do what I thought it does. I'm chatting quickly now with the operator-sdk team to see if there's a way to avoid watching all ConfigMaps across all namespaces.

**Comment by squeed** [comment]
OK, one small change needed: You also need to set `IsController: true` on the `handler.EnqueueRequestForOwner{}` parameter. Otherwise, this is fine.

**Comment by dougbtv** [comment]
@squeed thanks for the double check with the operator-sdk team! appreciate it. I've got a new fix up with the additional parameter `IsController: true` on the `handler.EnqueueRequestForOwner{}`

**Pull request merged**
