### PR TITLE
Bug 1778314:  False Alarm - SDN pod has gone too long without syncing iptables rule

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
cherry pick of PR https://github.com/openshift/cluster-network-operator/pull/390 to 4.2

Fixes Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1778314

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
but you need to fix the bugzilla bug

**Comment by squeed** [comment]
@JacobTanenbaum please fix BZ and let's get this in.

**Pull request merged**
