### PR TITLE
ovnk: Remove unused current_probe_interval when setting NB_Global name

### PR DESCRIPTION
**Pull request by andreaskaris**

### CODE REVIEW

**Comment by dcbw** [comment]
https://github.com/openshift/cluster-network-operator/pull/2037 does a similar cleanup FWIW, thanks for the idea!

**Comment by dcbw** [comment]
Mostly superceded by https://github.com/openshift/cluster-network-operator/pull/2037

**Comment by andreaskaris** [comment]
closing this then :)

**Pull request closed without merging**
