### PR TITLE
Bug 1914932: Put correct resource name in relatedObjects

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
Any chance to pass CI? :) 
/test e2e-gcp-ovn-upgrade

**Comment by tremes** [comment]
Can someone take a look at the CI failures pls? @squeed, @rcarrillocruz? I doubt it's related to my change, but maybe I am wrong.

**Comment by tremes** [comment]
@alexanderConstantinescu Hi, this PR reached the limit for the retest commands (that's why it's in pending state). I would need to force push to enable retesting again. Now this also requires a valid bugzilla to be able to merge it in 4.7. Can you please create some or what is your suggestion please?

**Comment by alexanderConstantinescu** [comment]
/retitle Bug 1914932: Put correct resource name in relatedObjects

@tremes : please feel free to force push to get over the hick-up with the CI bot.

**Comment by alexanderConstantinescu** [comment]
@tremes : could you also do a `/bugzilla refresh` when you re-push, I suspect the errors I am seeing is for the same reason you mentioned above. If force pushing does not work, could you re-open a new PR. 

Sorry about this.

**Comment by tremes** [comment]
@alexanderConstantinescu Thanks. I dd the force push so let's see if everything passes.

**Comment by tremes** [comment]
@alexanderConstantinescu OK so it's failing again. Is there any chance that someone would take a look at the failures please?

**Comment by alexanderConstantinescu** [comment]
/lgtm cancel
/hold

This PR is broken, it's deleting the CRD `networks.operator.openshift.io` on an update. I am trying to work out what is going on and fixing it.

**Comment by alexanderConstantinescu** [comment]
I opened https://github.com/openshift/cluster-network-operator/pull/945, which should fix the upgrade jobs. If that passes the upgrades: I will close this and use that instead. It's faster doing it like this, since code freeze is on Friday.

**Comment by alexanderConstantinescu** [comment]
Upgrades are passing on #945 , let's focus on that.

/close

**Comment by tremes** [comment]
@alexanderConstantinescu Interesting. Thanks

**Pull request closed without merging**
