### PR TITLE
ovnkube: export OVS metrics along with OVN metrics

### PR DESCRIPTION
**Pull request by dcbw**
Lets us finally get host OVS metrics with ovnkube.

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
migration-rollback issue is a flake
```
{Operator degraded (InvalidOperatorConfig): Not applying unsafe configuration change: invalid configuration: [cannot change default network type when not doing migration]. Use 'oc edit network.operator.openshift.io cluster' to undo the change.  Operator degraded (InvalidOperatorConfig): Not applying unsafe configuration change: invalid configuration: [cannot change default network type when not doing migration]. Use 'oc edit network.operator.openshift.io cluster' to undo the change.}
```

**Review by flavio-fernandes — COMMENTED** [review]
/lgtm

ref: https://github.com/ovn-org/ovn-kubernetes/pull/2924

**Comment by npinaeva** [comment]
@dcbw we should be careful about metrics we expose by default - need at least check naming conventions for all of them and verify the values too. So since I think we agreed that this is now mostly needed for perf/scale team I'd prefer to disable this by default, and let scale team enable it when needed. 
And we can do proper review and enabling by default for ovs metrics later, as a part of our debuggability effort. wdyt?

**Pull request merged**
