### PR TITLE
[release-4.12] Bug OCPBUGS-4896: Kuryr: If set use MTU from Config for svc net

### PR DESCRIPTION
**Pull request by dulek**
Cherry pick of #1586 adding fix from #1669.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Sweet, thanks @dulek!
/lgtm

**Comment by dulek** [comment]
/test e2e-openstack-kuryr

I forgot about this.

**Comment by dulek** [comment]
/retest-required

e2e-openstack-kuryr passes, other e2e-openstack jobs failures are unrelated.

**Comment by dulek** [comment]
@MaysaMacedo @eurijon: Can you take a look at this and add the labels it needs?

**Comment by dulek** [comment]
@MaysaMacedo @eurijon: Hey folks, it's been a while! Can you take a look at this and add the labels it needs?

**Pull request merged**
