### PR TITLE
Bug 1758656: Removes external api server from default noProxy

### PR DESCRIPTION
**Pull request by danehans**
4.2.z backport of https://bugzilla.redhat.com/show_bug.cgi?id=1757973

### CODE REVIEW

**Comment by squeed** [comment]
@danehans those tests are never going to pass, there is an error.

**Comment by danwinship** [comment]
/hold
to stop the bot from spamming retries. feel free to cancel after repushing

**Comment by danehans** [comment]
I had to pull in `ea9717ad` from the 4.2 branch to get the missing `valid_proxy_config_with_gcp_provider` test case that was failing.

/hold cancel

**Pull request merged**
