### PR TITLE
SDN-4726: Reapply "Merge pull request #2330 from pperiyasamy/block-sdn-upgrade"

### PR DESCRIPTION
**Pull request by danwinship**
This reverts commit 996fd663d5df72b450674356baa178c157c35e75.

/assign @pperiyasamy

### CODE REVIEW

**Comment by danwinship** [comment]
/hold
(for payload check...)

**Comment by danwinship** [comment]
/assign @neisw 

I think this is working? https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn-conformance/1783857121566134272 shows that it is passing `: [sig-arch][Early] Managed cluster should [apigroup:config.openshift.io] start all core operators [Skipped:Disconnected] [Suite:openshift/conformance/parallel]`

**Comment by neisw** [comment]
@danwinship -  Sorry PTO last Friday.  Yes the payload verification looks good.  Thanks for running it!

**Pull request merged**
