### PR TITLE
Bug 1764256: Handle kubeconfigs with an empty context.

### PR DESCRIPTION
**Pull request by squeed**
Fixes a nil panic for kubeconfigs with no context.

### CODE REVIEW

**Comment by danwinship** [comment]
Have you tested this against one of their weird kubeconfigs?

**Comment by squeed** [comment]
What in the heck is going on here!?

**Comment by squeed** [comment]
Ah, this got b0rken by the switch from master to 4.4. I'll have to close this and re-open against 4.3.

**Pull request closed without merging**
