### PR TITLE
OCPBUGS-10765: Remove oldest ovn acl log files when file limit exceeded

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/OCPBUGS-10765

**Comment by sjenning** [comment]
hypershift test was overridden on this PR and broke the CI release stream

https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-07-07-055606

**Pull request merged**
