### PR TITLE
OCPBUGS-20104: Don't run network node identity as root

### PR DESCRIPTION
**Pull request by jcaamano**

### CODE REVIEW

**Comment by jcaamano** [comment]
/retitle OCPBUGS-20104: Don't run network node identity as root

**Comment by abhat** [comment]
Do you need an additional CAP_NET to be able to bind to localhost in the nodes default network namespace?

**Comment by jcaamano** [comment]
> Do you need an additional CAP_NET to be able to bind to localhost in the nodes default network namespace?

Only for privileged ports < 1024 I believe

**Pull request merged**
