### PR TITLE
[release-4.13] OCPBUGS-22896: Remove oldest ovn acl log files when file limit exceeded

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
/assign @kyrtapz 
@kyrtapz , could you please take a look at this backport?

**Comment by jluhrsen** [comment]
> /assign @kyrtapz @kyrtapz , could you please take a look at this backport?

oh, sorry. I think you were an approver for this. I'll try to find one.

**Review by trozet — APPROVED** [review]
/approve

/label backport-risk-assessed

**Comment by flavio-fernandes** [comment]
super silly nit. Otherwise,
/lgtm

**Pull request merged**
