### PR TITLE
NO-JIRA: onv-k, udn: Update UserDefinedNetwork CRD

### PR DESCRIPTION
**Pull request by ormergi**
- localnet support is removed as its not supported yet
- Add missing markers to status conditions

### CODE REVIEW

**Comment by trozet** [comment]
/retitle NO-JIRA: onv-k, udn: Update UserDefinedNetwork CRD

**Comment by tssurya** [comment]
woohooo

**Comment by tssurya** [comment]
/retitle SDN-4930: ovn-k, udn: Update UserDefinedNetwork CRD

**Pull request merged**
