### PR TITLE
[release-4.14][WIP] fix conditions on IC upgrade not to let it interfere with cluster cidr expansion

### PR DESCRIPTION
**Pull request by ricky-rav**

### CODE REVIEW

**Comment by jluhrsen** [comment]
are we closing this in favor of https://github.com/openshift/cluster-network-operator/pull/2207

**Comment by ricky-rav** [comment]
yes, I'll close it and will remove the bug from the title.
If my other PR doesn't get much attention, we can resume this smaller PR and have it approved first :)

**Pull request closed without merging**
