### PR TITLE
Bug 1750991: Fixes http readinessEndpoint validation for httpsProxy

### PR DESCRIPTION
**Pull request by danehans**
Previously, a readiness endpoint with a https url scheme would be considered invalid if `httpsProxy` used a http scheme. It's common for clients to be configured with https proxies that contain an http url scheme. This PR updates `readinessEndpoint` validation to allow for this use case and also simplified the name of the http/https scheme constants.

### CODE REVIEW

**Comment by squeed** [comment]
As a matter of taste, disambiguating between `httpScheme` and `httpsScheme` is pretty hard for me. Given that these constants are, well, constant, I personally prefer to skip the variables and just spell them every time.

I'll leave that up to you. But if you keep the variables, I'd prefer `schemeHTTP` and `schemeHTTPS`, which are much easier to read.

**Comment by danehans** [comment]
@squeed I updated the constants.

**Pull request merged**
