### PR TITLE
Bug 1890130: openshift-sdn: multitenant: join openshift-etcd-operator to etcd

### PR DESCRIPTION
**Pull request by squeed**
It needs to be able to reach etcd, so it needs to be in netns 1.

Fixes: bz 1890130

### CODE REVIEW

**Comment by squeed** [comment]
/skip ci/prow/e2e-gcp-ovn

no ovn changes.

**Comment by squeed** [comment]
well, the multitenant cluster has come up and seems mostly fine, but we might have a bit more whack-a-mole to find connection issues.

**Comment by squeed** [comment]
looks like one node went unreachable - investigating (though this should have had no effect)

/test e2e-aws-sdn-multi

**Comment by squeed** [comment]
update: no real useful information; of course the node's logs are inaccessible. It's a worker node, so definitely not affected by this change.

**Comment by squeed** [comment]
argh, it looks like load took down a node:
```
RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = Kubelet may be retrying requests that are timing out in CRI-O due to system load
```

I think this will go in, eventually.

**Comment by juanluisvaladas** [comment]
Thje pod predicate nodeports error also happens in networkpolicy, we can ignore this.
https://search.ci.openshift.org/?search=Pod+Predicate+NodePorts+failed&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by squeed** [comment]
ordinarily I would just `/skip` this, but given that this is literally the CI job I'm trying to fix...

**Comment by squeed** [comment]
still crio creation timing out; this is really weird. Again, it doesn't immediately seem like a problem caused by my change.

**Comment by squeed** [comment]
/hold
something is definitely wrong; bumping osdn verbosity.

**Comment by danwinship** [comment]
> /skip ci/prow/e2e-gcp-ovn

(the word you're looking for is `/override`)

**Comment by squeed** [comment]
An update: I think there's a deadlock in openshift-sdn in multitenant mode. This PR exposes it, but I can't fix it in this repository.

I think we should force-merge this, so the test results are meaningful

**Comment by squeed** [comment]
It looks like multitenant mode is stuck on an sdn deadlock. Given that this change doesn't break anything, and gets us closer to fixing openshift-sdn multitenant, I'm going to override the job so we can make progress.

/override ci/prow/e2e-aws-sdn-multi
/override ci/prow/e2e-gcp-ovn

**Pull request merged**
