### PR TITLE
OCPBUGS-25688: remove microshift folder, since CNO doesn't manage it

### PR DESCRIPTION
**Pull request by npinaeva**
The initial attempt to integrate microshift with CNO didn't work, and microshift is built and configured in a different repo.
We may take another attempt to addsome integration but to ovn-k instread of CNO, tracked here https://issues.redhat.com/browse/NP-544

### CODE REVIEW

**Comment by npinaeva** [comment]
cc @kyrtapz @zshi-redhat @pliurh

**Comment by kyrtapz** [comment]
@npinaeva Thanks! Can you add the rationale we discussed to the PR description (for posterity!) 
Additionally there are also image references https://github.com/openshift/cluster-network-operator/blob/4443bc67102219f50382bf5d7019d125cb04ad3e/manifests/image-references#L49 which I am not sure are still required, maybe @zshi-redhat knows :)

**Comment by zshi-redhat** [comment]
> @npinaeva Thanks! Can you add the rationale we discussed to the PR description (for posterity!) Additionally there are also image references
> 
> https://github.com/openshift/cluster-network-operator/blob/4443bc67102219f50382bf5d7019d125cb04ad3e/manifests/image-references#L49
> which I am not sure are still required, maybe @zshi-redhat knows :)

[This](https://github.com/openshift/cluster-network-operator/pull/1556) is required to keep the ovn-kubernetes-microshift image in the release payload (see [here](https://docs.google.com/document/d/1CGZVEyuloZ9oD4NUArW6dnEpi0WFc6BP2tqPSwFZTCY/edit#heading=h.kbh7wlmo6f3t) for the process of building release payload).  ovn-kubernetes-microshift image was intentionally added to the payload for easily updating the microshift image-set and building the microshift binary/package.

**Comment by zshi-redhat** [comment]
LGTM

**Comment by jcaamano** [comment]
> > @npinaeva Thanks! Can you add the rationale we discussed to the PR description (for posterity!) Additionally there are also image references
> > https://github.com/openshift/cluster-network-operator/blob/4443bc67102219f50382bf5d7019d125cb04ad3e/manifests/image-references#L49
> > 
> > which I am not sure are still required, maybe @zshi-redhat knows :)
> 
> [This](https://github.com/openshift/cluster-network-operator/pull/1556) is required to keep the ovn-kubernetes-microshift image in the release payload (see [here](https://docs.google.com/document/d/1CGZVEyuloZ9oD4NUArW6dnEpi0WFc6BP2tqPSwFZTCY/edit#heading=h.kbh7wlmo6f3t) for the process of building release payload). ovn-kubernetes-microshift image was intentionally added to the payload for easily updating the microshift image-set and building the microshift binary/package.

Hopefully we don't forget about this. Adding a comment somewhere might be useful.

**Pull request merged**
