### PR TITLE
Bug 2034155: Adds back --disable-snat-multiple-gws

### PR DESCRIPTION
**Pull request by trozet**
This was accidentally removed in:
0f38cc7f233e09c795540be43bab291c8b857fe8

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
@tssurya PTAL

**Comment by tssurya** [comment]
thanks Tim!

**Comment by trozet** [comment]
@tssurya are we waiting on @alexanderConstantinescu  fixes to egress ip to address compatibility with disable snat multiple gws?

**Comment by tssurya** [comment]
we need https://github.com/ovn-org/ovn-kubernetes/pull/2725 to get in first before we can merge this PR.

**Comment by trozet** [comment]
@tssurya can we remove the hold now and merge?

**Comment by tssurya** [comment]
good news is that its definitely something in ovn-k parts, not the MCO parts. I am going to create a cluster and see why the operator pods like ingress are unable to reach the API service after reboot: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1288/pull-ci-openshift-cluster-network-operator-master-e2e-network-migration/1484542169451597824/artifacts/e2e-network-migration/gather-extra/artifacts/pods/openshift-ingress_router-default-55fcb47b5-46pmb_router.log

**Comment by tssurya** [comment]
I also want to see if the gcp-ovn job succeeds for a fresh cluster - triggered a retest for that.

**Comment by tssurya** [comment]
It seems like we are struggling to get the l3 gateway annotation after node reboot?:
```
E0121 16:07:47.013389       1 pods.go:529] unable to parse node L3 gw annotation: k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-173-96.us-west-1.compute.internal"
```
even before we used to do the same... Is it because ICNI was not enabled by default we weren't hitting this issue since the hidden config map was setting this value to false at least in the CI? The migration jobs are a recent addition.

**Comment by tssurya** [comment]
/lgtm cancel
to prevent wastage of CI resources.

**Comment by tssurya** [comment]
/hold
till we get https://github.com/ovn-org/ovn-kubernetes/pull/2765 downstream.
(https://bugzilla.redhat.com/show_bug.cgi?id=2043961)

**Comment by tssurya** [comment]
@trozet : oh look this PR finally merged after I don't know how many battles.

**Pull request merged**
