### PR TITLE
: Bug 1913399: Bump flow control apiVersion to beta

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Based on comment https://github.com/openshift/cluster-network-operator/pull/920#discussion_r552553510

/assign @sttts

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
/hold 

until after code freeze, see: https://github.com/openshift/cluster-network-operator/pull/920#discussion_r553374243

**Comment by sttts** [comment]
/retest
/lgtm
/approve

For 4.8.

**Comment by alexanderConstantinescu** [comment]
/retitle: Bug 1913399: Bump flow control apiVersion to beta

/assign @squeed

**Comment by alexanderConstantinescu** [comment]
/hold cancel

since code freeze is over

**Pull request merged**
