### PR TITLE
NP-615: Bump github.com/openshift/api

### PR DESCRIPTION
**Pull request by kyrtapz**
This PR bumps Bump github.com/openshift/api.

### CODE REVIEW

**Comment by jcaamano** [comment]
@kyrtapz for the IPv6 MTU migration there is also something fishy with the `ns/openshift-cloud-controller-manager-operator` that also does not look related to this change.

**Comment by kyrtapz** [comment]
> @kyrtapz for the IPv6 MTU migration there is also something fishy with the `ns/openshift-cloud-controller-manager-operator` that also does not look related to this change.

This hob is really flaky in general, I agree that the failures  do not look related to the introduced changes (my changes are not ipv6 specific)

**Comment by jcaamano** [comment]
> > @kyrtapz for the IPv6 MTU migration there is also something fishy with the `ns/openshift-cloud-controller-manager-operator` that also does not look related to this change.
> 
> This job is really flaky in general, I agree that the failures do not look related to the introduced changes (my changes are not ipv6 specific)

Have you seen this now?
```
 [sig-arch] Managed cluster should only include cluster daemonsets that have maxUnavailable or maxSurge update of 10 percent or maxUnavailable of 33 percent [Suite:openshift/conformance/parallel] expand_less
Run #0: Failed expand_less	4s
{  fail [github.com/openshift/origin/test/extended/operators/daemon_set.go:105]: Daemonsets found that do not meet platform requirements for update strategy:
  expected daemonset openshift-network-node-identity/network-node-identity to have maxUnavailable 10% or 33% (see comment) instead of 0, or maxSurge 10% instead of 100%
Ginkgo exit error 1: exit with code 1}
```

**Comment by kyrtapz** [comment]
> > > @kyrtapz for the IPv6 MTU migration there is also something fishy with the `ns/openshift-cloud-controller-manager-operator` that also does not look related to this change.
> > 
> > 
> > This job is really flaky in general, I agree that the failures do not look related to the introduced changes (my changes are not ipv6 specific)
> 
> Have you seen this now?
> 
> ```
>  [sig-arch] Managed cluster should only include cluster daemonsets that have maxUnavailable or maxSurge update of 10 percent or maxUnavailable of 33 percent [Suite:openshift/conformance/parallel] expand_less
> Run #0: Failed expand_less	4s
> {  fail [github.com/openshift/origin/test/extended/operators/daemon_set.go:105]: Daemonsets found that do not meet platform requirements for update strategy:
>   expected daemonset openshift-network-node-identity/network-node-identity to have maxUnavailable 10% or 33% (see comment) instead of 0, or maxSurge 10% instead of 100%
> Ginkgo exit error 1: exit with code 1}
> ```

Talked offline, the mentioned failure is not from this PR

**Comment by mkowalski** [comment]
/lgtm

We need this. If this doesn't make it soon, the whole onprem's team work for this cycle will be reverted (because we cannot ship a change without a backing implementation, and the only missing bit is blocked by this here, cc @davegord)

**Comment by kyrtapz** [comment]
e2e-network-mtu-migration-ovn-ipv6 passed :tada: 


> You folks wait with this, we are reverting on-prem's stuff from openshift/api right now and you will need to revendor anyway
> 
> ([openshift/api#1694](https://github.com/openshift/api/pull/1694))

@jcaamano not sure what we do here. Is it: wait for the revert to get in, revendor and fight CI?

**Comment by jcaamano** [comment]
> e2e-network-mtu-migration-ovn-ipv6 passed 🎉
> 
> > You folks wait with this, we are reverting on-prem's stuff from openshift/api right now and you will need to revendor anyway
> > ([openshift/api#1694](https://github.com/openshift/api/pull/1694))
> 
> @jcaamano not sure what we do here. Is it: wait for the revert to get in, revendor and fight CI?

I guess. But should be easier because the next around we will go with just required jobs. Let me know if you would like to do something else, epscially if this is blocking you critically.

**Comment by jcaamano** [comment]
/lgtm
/approve
/hold

Holding until @kyrtapz is satisfied with CI results. I am ok with `Required` passing since we already had plenty of greens with the previous API bump. Perhaps also upgrade jobs should pass.

**Pull request merged**
