### PR TITLE
Bug 1832311: Kuryr: Tighten security groups

### PR DESCRIPTION
**Pull request by dulek**
This PR ensures the security group are limiting access
to the minimum required.

### CODE REVIEW

**Comment by dulek** [comment]
@MaysaMacedo @luis5tb

**Comment by dulek** [comment]
This blocks https://github.com/openshift/cluster-network-operator/pull/637 and needs to get in before it.

**Comment by sdodson** [comment]
/retitle Bug 1832311: Kuryr: Tighten security groups

**Pull request merged**
