### PR TITLE
Bug 1909791: Fix EndpointSlice addition to standalone kube-proxy RBAC role

### PR DESCRIPTION
**Pull request by danwinship**
#926 was supposed to fix this but I actually added support for watching "v1.EndpointSlice", not "discoveryv1.EndpointSlice".

/hold
until I test it

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
ups

**Comment by danwinship** [comment]
it works
/hold cancel

**Comment by danwinship** [comment]
Not sure why this isn't merging since it's only optional jobs that are failing, but anyway, the change does not affect any of those jobs. (It only affects https://github.com/openshift/release/pull/12502 which can't merge until this does.)

/override ci/prow/e2e-aws-ovn-windows
/override ci/prow/e2e-aws-ovn-windows-custom-vxlan
/override ci/prow/e2e-azure-ovn
/override ci/prow/e2e-openstack-ovn
/override ci/prow/e2e-ovn-ipsec-step-registry
/override ci/prow/e2e-vsphere-ovn

**Pull request merged**
