### PR TITLE
Bug 1931997: mark network-check-target non critical

### PR DESCRIPTION
**Pull request by fedepaol**
The network-check-target ds is not critical for the network  functionality, and thus we mark it as non critical in order for it not to prevent upgrades if all the pods are not able to be scheduled.

### CODE REVIEW

**Comment by abhat** [comment]
> _No description provided._

nit: Please consider adding a description for this PR.

**Comment by abhat** [comment]
We should perhaps add the `maxUnavailable` daemonset option here? Refer to: #996.

**Comment by abhat** [comment]
overall LGTM.

**Comment by fedepaol** [comment]
> We should perhaps add the `maxUnavailable` daemonset option here? Refer to: #996.



> > We should perhaps add the `maxUnavailable` daemonset option here? Refer to: #996.
> 
> Do you mean in addition to `non-critical` ?
> I'd keep it consistent to what it was done for network-check-target [67d2391](https://github.com/openshift/cluster-network-operator/commit/67d2391d6b7a830634d7d0659673b70d4293783b)

I went through the thread related to https://github.com/openshift/cluster-network-operator/pull/996 and other bugs, I think this DS fell out of the radar. Will add it

**Comment by fedepaol** [comment]
@abhat I preferred filing a new bz / opening a new pr do address the `maxUnavailable` to keep this PR associated with the bz.

**Pull request merged**
