### PR TITLE
Bug 1945333: Backport of maxUnavailable for nw-checks

### PR DESCRIPTION
**Pull request by bpickard22**
Backporting fix from here https://github.com/openshift/cluster-network-operator/commit/02c6b3e6df7523339774d3381c3d584760dd5ce3#diff-8f4290a3005ea069[%E2%80%A6]ce049190063bface33f56a to 4.7

### CODE REVIEW

**Comment by astoycos** [comment]
Make sure you open the PR against the right branch :)

**Comment by bpickard22** [comment]
backport did not fix network- check-source and network-check-target
I have opened a new BZ in 4.8 and when that fix gets in I will backport that to 4.7 and open a new pr

**Pull request closed without merging**
