### PR TITLE
Bug 1809204: [4.4] Metrics exposed over insecure channel

### PR DESCRIPTION
**Pull request by aneeshkp**
This is backporting of #563

### CODE REVIEW

**Comment by dougbtv** [comment]
/retitle Bug 1809204: Metrics exposed over insecure channel

**Comment by danwinship** [comment]
/hold
since the PR this is a backport of is being reverted

**Comment by knobunc** [comment]
I suggest you close this and do a `/backport 4.4` when https://github.com/openshift/cluster-network-operator/pull/563 lands

**Comment by aneeshkp** [comment]
@knobunc  #563  is merged now, can I close this and add /backport 4.4 on #563?

**Comment by aneeshkp** [comment]
This is backporting of #563

**Pull request closed without merging**
