### PR TITLE
OCPBUGS-22896: run update-codegen after adding maxLogFiles cfg

### PR DESCRIPTION
**Pull request by jluhrsen**
this was missed in the PR [0] that introduced this new config param for the bug [1] to limit log file storage consumtion.

[0] https://github.com/openshift/cluster-network-operator/pull/2097
[1] https://issues.redhat.com/browse/OCPBUGS-22896

### CODE REVIEW

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/OCPBUGS-22896

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Pull request merged**
