### PR TITLE
OCPBUGS-18785: SDN controller manifest: add node name from downward kapi to sdn controller

### PR DESCRIPTION
**Pull request by martinkennelly**
/hold 

Depends on https://github.com/openshift/sdn/pull/578

### CODE REVIEW

**Comment by martinkennelly** [comment]
Waiting on CI to see if the rollout of SDN is ok even with the new flag.
Plan is to merge this then openshift/sdn#578

**Comment by martinkennelly** [comment]
/retest

Some jobs failed image wasnt updated.

**Comment by martinkennelly** [comment]
/unhold

SDN PR merged.

**Comment by martinkennelly** [comment]
/test e2e-aws-hypershift-ovn-kubevirt 
Test was killed and didnt complete. Unrelated to this PR.
```
[36mINFO[0m[2023-10-11T10:29:32Z] Running step e2e-aws-hypershift-ovn-kubevirt-conformance-tests. 
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s 
```

**Comment by martinkennelly** [comment]
@dcbw we're looking good. The remaining jobs are OVN-K specific.

**Comment by zhaozhanqi** [comment]
trying to pre-merge testing with cluster-bot with `launch openshift/cluster-network-operator#2047 azure,sdn`, but sounds like the sdn-controller pod is crashed. see job below

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure-modern/1712657961450475520

**Comment by martinkennelly** [comment]
/hold

I am seeing the same even though the CI is ok. Investigating.

**Comment by martinkennelly** [comment]
/unhold

@zhaozhanqi use the latest nightly explicitly and it works:

```
launch 4.15.0-0.nightly-2023-10-13-073920,openshift/cluster-network-operator#2047 azure,sdn
```

**Comment by zhaozhanqi** [comment]
> /unhold
> 
> @zhaozhanqi use the latest nightly explicitly and it works:
> 
> ```
> launch 4.15.0-0.nightly-2023-10-13-073920,openshift/cluster-network-operator#2047 azure,sdn
> ```

Yes, using the latest 4.15 nightly build is ok for this testing. Thanks.

**Comment by martinkennelly** [comment]
@dcbw We are looking good here.
Thanks @zhaozhanqi

**Comment by martinkennelly** [comment]
@dcbw bump :P Thank you!

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-ovn-windows

```
[36mINFO[0m[2023-10-24T18:44:16Z] Step e2e-vsphere-ovn-windows-windows-e2e-operator-test-with-custom-vxlan-port succeeded after 1h5m10s. 
[36mINFO[0m[2023-10-24T18:44:16Z] Step phase test succeeded after 1h5m10s.     
<snip>
error: gather did not start for pod must-gather-mbck5: unable to pull image: ImagePullBackOff: Back-off pulling image "registry.apps.build02.vmc.ci.openshift.org/ci-op-k955zrcc/stable@sha256:4ce94d9af1c311d54b7fa2bc592bd6200c7071b54fe671db6b9859844bea7e38"
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-24T18:45:01Z"}
error: failed to execute wrapped command: exit status 1 
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

is not even an SDN job

**Pull request merged**
