### PR TITLE
[release-4.14] OCPBUGS-11550: AUTH: update cluster-reader to include k8s.ovn.org

### PR DESCRIPTION
**Pull request by flavio-fernandes**
API group "k8s.ovn.org" should be included to cluster-reader role. That group has the following resources:
    - EgressFirewall
    - EgressIP
    - EgressQoS

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
Verified this change by deploying OCP with the new cluster role:
```
vagrant@devmaster ~/dev/openshift-apiserver.git OCPBUGS-11550_k8s.ovn.org*
❯ oc auth can-i list egressfirewalls --as=test --as-group=mylocaladmins
no

❯ oc --user=admin create secret generic htpasswd --from-file=htpasswd -n openshift-config
secret/htpasswd created

❯ oc replace -f - <<API
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: Local Password
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd
API
oauth.config.openshift.io/cluster replaced

❯ oc adm groups new mylocaladmins
group.user.openshift.io/mylocaladmins created

❯ oc adm groups add-users mylocaladmins test
group.user.openshift.io/mylocaladmins added: "test"

❯ oc adm policy add-cluster-role-to-group cluster-reader mylocaladmins
clusterrole.rbac.authorization.k8s.io/cluster-reader added: "mylocaladmins"

❯ oc auth can-i create pods --as=test --as-group=mylocaladmins
no

❯ oc auth can-i list pods --as=test --as-group=mylocaladmins
yes

❯ oc auth can-i list egressips --as=test --as-group=mylocaladmins
Warning: resource 'egressips' is not namespace scoped in group 'k8s.ovn.org'

yes

❯ oc auth can-i list egressfirewalls --as=test --as-group=mylocaladmins
yes

❯ oc auth can-i create egressfirewalls --as=test --as-group=mylocaladmins
no

❯ oc describe ClusterRole openshift-ovn-kubernetes-cluster-reader
Name:         openshift-ovn-kubernetes-cluster-reader
Labels:       rbac.authorization.k8s.io/aggregate-to-cluster-reader=true
Annotations:  <none>
PolicyRule:
  Resources                    Non-Resource URLs  Resource Names  Verbs
  ---------                    -----------------  --------------  -----
  egressfirewalls.k8s.ovn.org  []                 []              [get list watch]
  egressips.k8s.ovn.org        []                 []              [get list watch]
  egressqoses.k8s.ovn.org      []                 []              [get list watch]

❯ oc get ClusterRole cluster-reader -oyaml | grep -B1 -A9 ovn
- apiGroups:
  - k8s.ovn.org
  resources:
  - egressfirewalls
  - egressips
  - egressqoses
  verbs:
  - get
  - list
  - watch
- apiGroups:
```

**Comment by flavio-fernandes** [comment]
Some cool references on the aggregation support:
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/#:~:text=Aggregated%20ClusterRoles,-You%20can%20aggregate%20several%20ClusterRoles
- https://github.com/kubernetes/enhancements/issues/502
- https://github.com/kubernetes/kubernetes/pull/54005

**Comment by flavio-fernandes** [comment]
@kyrtapz PTAL

**Comment by flavio-fernandes** [comment]
Original change was done at the wrong (not as good) place, tracked in this PR that is not closed:  
https://github.com/openshift/openshift-apiserver/pull/363

**Review by trozet — APPROVED** [review]
/approve

**Pull request merged**
