### PR TITLE
Bug 1959185: Backport rbac proxy init script fixes

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by jluhrsen** [comment]
/retitle Bug 1891023: Backport rbac proxy init script fixes

**Comment by dcbw** [comment]
Bug bumped to urgent priority because it blocks most 4.6 networking CI jobs.

/bugzilla refresh

**Comment by jluhrsen** [comment]
@dcbw , we are going to need to override the failing CI.

**Comment by squeed** [comment]
/override ci/prow/e2e-vsphere-ovn
/override ci/prow/e2e-aws-ovn-windows-custom-vxlan

Jobs are broken, this PR is fine.

**Comment by squeed** [comment]
/override ci/prow/e2e-vsphere-ovn
/override ci/prow/e2e-aws-ovn-windows-custom-vxlan
to stop the retests.

**Pull request merged**
