### PR TITLE
Bug 1778235: network operator crashes when infra.status.platformStatus is missing

### PR DESCRIPTION
**Pull request by rcarrillocruz**

### CODE REVIEW

**Comment by squeed** [comment]
You've got a syntax error:

**Comment by rcarrillocruz** [comment]
I don't get it, works for me locally, both 1.12 and 1.13:

[ricky@ricky-laptop cluster-network-operator]$ gvm list

gvm gos (installed)

   go1.10.8
   go1.11.10
=> go1.12
   system

[ricky@ricky-laptop cluster-network-operator]$ GOPATH=~/go/ hack/build-go.sh 
Using version from git...
Building github.com/openshift/cluster-network-operator/cmd/cluster-network-operator (d52d6b97)
Building github.com/openshift/cluster-network-operator/cmd/cluster-network-renderer (d52d6b97)


[ricky@ricky-laptop cluster-network-operator]$ hack/build-go.sh 
Using version from git...
Building github.com/openshift/cluster-network-operator/cmd/cluster-network-operator (d52d6b97)
Building github.com/openshift/cluster-network-operator/cmd/cluster-network-renderer (d52d6b97)
[ricky@ricky-laptop cluster-network-operator]$ go version
go version go1.13.4 linux/amd64

**Comment by alexanderConstantinescu** [comment]
/lgtm

I guess you might want to do a bugzilla update to refresh the reference.

**Pull request merged**
