### PR TITLE
SDN-4061: Remove interconnect upgrade logic, single-zone YAMLs and everything related to OVNK centralized architecture

### PR DESCRIPTION
**Pull request by ricky-rav**

### CODE REVIEW

**Comment by ricky-rav** [comment]
@kyrtapz Could you have a look at the last commit (`Remove everything related to hypershift SBDB route`)? Thanks :)

**Comment by kyrtapz** [comment]
> @kyrtapz Could you have a look at the last commit (`Remove everything related to hypershift SBDB route`)? Thanks :)

I reviewed 23b758650fd6a91bbea398c3a3b429f8d7114b9e and it looks good to me!

**Review by trozet — APPROVED** [review]
dualstack might be broken. The dualstack jobs are all permafail recently anyway. The metal dualstack job doesnt seem to exist for CNO. We should watch that job carefully after we merge this.

There's no way I can review every line of this PR. I went over what I could; it looks good and passes CI, so lets get it in and go from there.

/lgtm

**Pull request merged**
