### PR TITLE
Add OWNERS files for openstack components.

### PR DESCRIPTION
**Pull request by squeed**

### CODE REVIEW

**Comment by squeed** [comment]
cc @dulek

**Comment by danwinship** [comment]
FTR, although it's ugly, it's possible to have file-level reviewers (eg, for `pkg/network/kuryr.go`). eg, see [`k/k/OWNERS`](https://github.com/kubernetes/kubernetes/blob/master/OWNERS).

Also, we could make use of `OWNERS_ALIASES` to avoid duplicating the list of kuryr hackers in multiple places

**Comment by squeed** [comment]
Updated to use aliases, good point. That regex business looks like more trouble than it's worth :-).

**Comment by squeed** [comment]
aws grumpiness
/retest

**Pull request merged**
