### PR TITLE
Remove ability to deploy with Kuryr

### PR DESCRIPTION
**Pull request by dulek**
Kuryr is deprecated since 4.12, this removes CNO's ability to deploy with Kuryr.

### CODE REVIEW

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
/hold cancel

now that https://github.com/openshift/release/pull/44113 is merged

**Comment by dulek** [comment]
Ouch, this was supposed to wait for https://github.com/openshift/release/pull/44117.

**Pull request merged**
