### PR TITLE
Bug 1942603: [release-4.7] Allow from router policy support for cluster network operator

### PR DESCRIPTION
**Pull request by abhat**
This PR backports the commits relevant for allow-from-router feature for 4.7.

### CODE REVIEW

**Comment by asood-rh** [comment]
/lgtm

Used the PR to build image registry.build01.ci.openshift.org/ci-ln-108qgx2/release:latest to create a OVNKubernetes cluster in vSphere to test allow from router traffic policy with both labels.

**Comment by asood-rh** [comment]
@abhat Could you look at missing label of the policy-group.network.openshift.io/ingress= for cloud provider aws?

The allow-from-router policy with new label did not work on AWS.
This is how namespace openshift-ingress looks.

 oc describe ns openshift-ingress
Name:         openshift-ingress
Labels:       name=openshift-ingress
              network.openshift.io/policy-group=ingress
              olm.operatorgroup.uid/d06f3948-2ecd-4246-9a07-6065c7e874ec=
              openshift.io/cluster-monitoring=true
Annotations:  openshift.io/node-selector: 
              openshift.io/sa.scc.mcs: s0:c24,c19
              openshift.io/sa.scc.supplemental-groups: 1000590000/10000
              openshift.io/sa.scc.uid-range: 1000590000/10000
Status:       Active

No resource quota.

No LimitRange resource.

**Comment by sdodson** [comment]
/hold cancel
openshift/ovn-kubernetes#526 has merged

**Comment by sdodson** [comment]
Clearing stale cherry-pick-approved, please investigate the persistent test failure.

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.70

approved

**Pull request merged**
