### PR TITLE
OCPBUGS-27222: Fix CloudPrivateIPConfig CRD in common

### PR DESCRIPTION
**Pull request by dulek**
`update-codegen.sh` only updated the top-level CRD as 001-crd.yaml in
`/bindata/cloud-network-config-controller` and skipped the one in
`common` subdirectory. This made https://github.com/openshift/cluster-network-operator/pull/2246 to not actually update the CRD.

This commit makes sure the script is updated to put the file into the
correct subdirectory.

### CODE REVIEW

**Comment by dulek** [comment]
Hey @kyrtapz, this  is an interesting one!

**Comment by kyrtapz** [comment]
Oh...
https://github.com/openshift/cluster-network-operator/commit/aa22e33a2bd7c2ab20f451f888653b07e9c1d5b5#diff-79695d931c29b18427fe2b7f9d3f2e767501282dac50b5c47f833e3f43fd6462 erroneously brought the file to the top level directory because the `update-codegen.sh` script was not updated to use the `common` subdir.
Could you change the script to:
```
echo "${HEADER}" > bindata/cloud-network-config-controller/common/001-crd.yaml
cat vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml >> bindata/cloud-network-config-controller/common/001-crd.yaml
```
And remove the top level CRD? It is not actually used.

**Comment by dulek** [comment]
> Oh... [aa22e33#diff-79695d931c29b18427fe2b7f9d3f2e767501282dac50b5c47f833e3f43fd6462](https://github.com/openshift/cluster-network-operator/commit/aa22e33a2bd7c2ab20f451f888653b07e9c1d5b5#diff-79695d931c29b18427fe2b7f9d3f2e767501282dac50b5c47f833e3f43fd6462) erroneously brought the file to the top level directory because the `update-codegen.sh` script was not updated to use the `common` subdir. Could you change the script to:
> 
> ```
> echo "${HEADER}" > bindata/cloud-network-config-controller/common/001-crd.yaml
> cat vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml >> bindata/cloud-network-config-controller/common/001-crd.yaml
> ```
> 
> And remove the top level CRD? It is not actually used.

Sure, I wasn't sure what's the correct way to fix this. Thank you!

**Comment by dulek** [comment]
@kyrtapz: Could you take another look?

**Comment by dulek** [comment]
/cherry-pick release-4.15

Let's see if this will apply cleanly.

**Pull request merged**
