### PR TITLE
OCPBUGS-11503: update 4.13 Dockerfile to use rhel-8 and go 1.19

### PR DESCRIPTION
**Pull request by jluhrsen**

### CODE REVIEW

**Comment by kyrtapz** [comment]
@jluhrsen considering we are [changing](https://github.com/openshift/release/pull/38079/files#diff-bc90ab44b5f9d9bb692c2603adc7431bf6903553d17d40d249036f7330f25f23R22) the release dockerfile from `Dockerfile.rhel7` to `Dockerfile` I assume we also need to update the second base image from:
 `FROM registry.ci.openshift.org/openshift/origin-v4.0:base` 
to:
 `FROM registry.ci.openshift.org/ocp/4.13:base`

This would match what the bot did in 4.14: https://github.com/openshift/cluster-network-operator/pull/1768

**Comment by jluhrsen** [comment]
> @jluhrsen considering we are [changing](https://github.com/openshift/release/pull/38079/files#diff-bc90ab44b5f9d9bb692c2603adc7431bf6903553d17d40d249036f7330f25f23R22) the release dockerfile from `Dockerfile.rhel7` to `Dockerfile` I assume we also need to update the second base image from: `FROM registry.ci.openshift.org/openshift/origin-v4.0:base` to: `FROM registry.ci.openshift.org/ocp/4.13:base`
> 
> This would match what the bot did in 4.14: #1768

yes, thanks for catching that. it's updated now.

**Review by trozet — APPROVED** [review]

**Pull request merged**
