### PR TITLE
dep ensure -update github.com/openshift/api

### PR DESCRIPTION
**Pull request by s1061123**
Also changes "operv1.ProxyArgumentList" to fix build error

### CODE REVIEW

**Comment by s1061123** [comment]
thank you for the review, @danwinship!

**Comment by squeed** [comment]
Hmm, not sure what's up with CI.
/refresh

**Comment by s1061123** [comment]
We get the result for e2e-aws and upgrade may take 2h to complete (from my last result).
Let's see the result...

**Pull request merged**
