### PR TITLE
OCPBUGS-36499: [release-4.15] Bump Openshift API and backport configurable subnet knobs (transit / join / masquerade)

### PR DESCRIPTION
**Pull request by bpickard22**
Adds the necessary knobs in the cno to consume the api change exposing the internal masquerade subnet in ovn-k where we reserve addresses for ip masquerading

Had to rebase on top of small conflict with addition of logging for libovsdb in the config yamls

Also adds unit tests and verification in cno for configured masquerade subnets and corrects some tests/verification of the join subnet

Also applies fix from OCPBUGS-33728, which corrects the key names and adds the config to the managed cluster side

Signed-off-by: Ben Pickard <bpickard@redhat.com>
(cherry picked from commit 1b4d11dcfe7536375c34c8994d4051d3c3d8c53d)

s

### CODE REVIEW

**Comment by bpickard22** [comment]
cc @kyrtapz

**Comment by kyrtapz** [comment]
@bpickard22 you will need to link a bug to meet the label requirements,

**Comment by kyrtapz** [comment]
/retest
@arghosh93 PTAL

**Comment by arghosh93** [comment]
I have checked the backport and tested after creating a cluster from this PR. Looks good to me.
/lgtm

**Pull request merged**
