### PR TITLE
OCPBUGS-17677: [Azure] Add granular permission for assigning egressIP to NIC to Azure CredentialsRequest for workload identity.

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by abutcher** [comment]
The two required windows tests for `e2e-{aws,vsphere}-ovn-windows` have the same failure afaict.

`e2e-aws-ovn-windows`:

```
WMCO deployment has no available replicas
```

[Pod logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1949/pull-ci-openshift-cluster-network-operator-master-e2e-aws-ovn-windows/1691794057455472640/artifacts/e2e-aws-ovn-windows/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-7f964c858f-j8dwg_manager.log):
```
2023-08-16T13:29:41Z	INFO	version	operator	{"version": "9.0.0-aa5e4bf-dirty"}
2023-08-16T13:29:41Z	INFO	version	go	{"version": "go1.20.3 linux/amd64"}
2023-08-16T13:29:41Z	INFO	leader	Trying to become the leader.
2023-08-16T13:29:41Z	DEBUG	leader	Found podname	{"Pod.Name": "windows-machine-config-operator-7f964c858f-j8dwg"}
2023-08-16T13:29:41Z	DEBUG	leader	Found Pod	{"Pod.Namespace": "openshift-windows-machine-config-operator", "Pod.Name": "windows-machine-config-operator-7f964c858f-j8dwg"}
2023-08-16T13:29:41Z	INFO	leader	Found existing lock with my name. I was likely restarted.
2023-08-16T13:29:41Z	INFO	leader	Continuing as the leader.
2023-08-16T13:29:41Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "0.0.0.0:9182"}
2023-08-16T13:29:41Z	ERROR	controller.secret	Unable to retrieve private key, please ensure it is created	{"error": "the cache is not started, can not read objects"}
github.com/openshift/windows-machine-config-operator/controllers.(*SecretReconciler).SetupWithManager
	/build/windows-machine-config-operator/controllers/secret_controller.go:64
main.main
	/build/windows-machine-config-operator/cmd/operator/main.go:201
runtime.main
	/usr/lib/golang/src/runtime/proc.go:250
2023-08-16T13:29:41Z	ERROR	setup	unable to create ConfigMap reconciler	{"error": "error creating ignition object: failed to parse MachineConfig ignition: unsupported config version\nReport: "}
main.main
	/build/windows-machine-config-operator/cmd/operator/main.go:212
runtime.main
	/usr/lib/golang/src/runtime/proc.go:250
```

---

`e2e-vsphere-ovn-windows`:

```
WMCO deployment has no available replicas
```

[Pod logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1949/pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-windows/1691794057484832768/artifacts/e2e-vsphere-ovn-windows/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-7dd78dfc7c-pl6sg_manager.log):
```
2023-08-16T15:22:57Z	INFO	version	operator	{"version": "9.0.0-aa5e4bf-dirty"}
2023-08-16T15:22:57Z	INFO	version	go	{"version": "go1.20.3 linux/amd64"}
2023-08-16T15:22:57Z	INFO	leader	Trying to become the leader.
2023-08-16T15:22:57Z	DEBUG	leader	Found podname	{"Pod.Name": "windows-machine-config-operator-7dd78dfc7c-pl6sg"}
2023-08-16T15:22:57Z	DEBUG	leader	Found Pod	{"Pod.Namespace": "openshift-windows-machine-config-operator", "Pod.Name": "windows-machine-config-operator-7dd78dfc7c-pl6sg"}
2023-08-16T15:22:57Z	INFO	leader	Found existing lock with my name. I was likely restarted.
2023-08-16T15:22:57Z	INFO	leader	Continuing as the leader.
2023-08-16T15:22:57Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "0.0.0.0:9182"}
2023-08-16T15:22:57Z	ERROR	controller.secret	Unable to retrieve private key, please ensure it is created	{"error": "the cache is not started, can not read objects"}
github.com/openshift/windows-machine-config-operator/controllers.(*SecretReconciler).SetupWithManager
	/build/windows-machine-config-operator/controllers/secret_controller.go:64
main.main
	/build/windows-machine-config-operator/cmd/operator/main.go:201
runtime.main
	/usr/lib/golang/src/runtime/proc.go:250
2023-08-16T15:22:57Z	ERROR	setup	unable to create ConfigMap reconciler	{"error": "error creating ignition object: failed to parse MachineConfig ignition: unsupported config version\nReport: "}
main.main
	/build/windows-machine-config-operator/cmd/operator/main.go:212
runtime.main
	/usr/lib/golang/src/runtime/proc.go:250
```

**Comment by newtonheath** [comment]
@abutcher so read that failures are due to CI availability vs issues with code
@abhat @dcbw can we push this through or do you have concerns? even if concern are you ok with oking CCO-294 while this fix happens in coming days if required?
cc: @jianping-shu @huangmingxia @huiran0826

**Comment by zshi-redhat** [comment]
tide seems stuck in "Not mergeable Retesting 14 jobs" state for the last 3 days, running retest.

/retest-required

**Pull request merged**
