### PR TITLE
Bug 1932114: Detect Nodes Network MTU

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This commit adds the support to detect the Nodes
Network MTU so that the Namespace Networks use the
same MTU as the host.

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Review by JAORMX — APPROVED** [review]

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.50

approved

**Pull request merged**
