### PR TITLE
Bug 1908914: OVN-Kubernetes: upgrade node before master, downgrade master before node Upgrade ovn node first

### PR DESCRIPTION
**Pull request by squeed**
This includes the following changes:

- A few utility methods for updating lists of objects
- A semver-direction utility
- The upgrade & downgrade logic for ovnk
- Decrease re-reconcile interval to 3 minutes

/cc @dcbw
/cc @danwinship
/cc @alexanderConstantinescu

### CODE REVIEW

**Comment by squeed** [comment]
test results look good
/retest
this is probably ready for lgtm

**Comment by squeed** [comment]
Okay, rebased
@dcbw can you lgtm please? Before it gets another merge conflict.

**Comment by squeed** [comment]
gcp api issues
/retest

**Comment by dcbw** [comment]
gcp lease capacity issues
/retest

**Pull request merged**
