### PR TITLE
OCPBUGS-17677: [Azure]CNCC failed to assign egressIP to NIC for Azure Workload Identity Cluster

### PR DESCRIPTION
**Pull request by abutcher**
Adds additional missing permission `Microsoft.Network/loadBalancers/backendAddressPools/join/action`.

OCPBUGS-17677
/cc @huiran0826

### CODE REVIEW

**Comment by abutcher** [comment]
@huiran0826 Is it possible to retest this with clusterbot workflow with the PR?

**Comment by sdodson** [comment]
@zshi-redhat When do we think we can have these proposed permissions reviewed and approved?

**Comment by kyrtapz** [comment]
/lgtm
Although I haven't tested the change it looks reasonable to add that permission because we are attatching the interface to the backendAddressPool:
https://github.com/openshift/cloud-network-config-controller/blob/master/pkg/cloudprovider/azure.go#L162

**Comment by zshi-redhat** [comment]
> @zshi-redhat When do we think we can have these proposed permissions reviewed and approved?

@sdodson  Patryk just reviewed, we will have another eye on it and approve it tomorrow if not today.

**Review by trozet — APPROVED** [review]
/approve

**Pull request merged**
