### PR TITLE
KIND deployments for CNO fails.

### PR DESCRIPTION
**Pull request by Billy99**
KIND deployments for CNO are failing due to a requirement for existence of
"cluster-config-v1" configMap introduced by merge c594414 on 03/09/2020. This
change adds a minimal "cluster-config-v1" configMap to KIND deployments.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

### CODE REVIEW

**Comment by Billy99** [comment]
@trozet PTAL

**Comment by trozet** [comment]
@danwinship PTAL

**Comment by alexanderConstantinescu** [comment]
Instead of hard-coding `NUM_MASTER_NODES=1` maybe you could run a `grep -c "role\: control-plane" hack/kind.yaml` and remove the commented lines in that file? 

Besides that, thanks for fixing this!

**Comment by Billy99** [comment]
> Instead of hard-coding `NUM_MASTER_NODES=1` maybe you could run a `grep -c "role\: control-plane" hack/kind.yaml` and remove the commented lines in that file?
> 
> Besides that, thanks for fixing this!

Thanks for the suggestion, Will do.

**Pull request merged**
