### PR TITLE
Revert "OCPBUGS-12856: Support Device Plugin Resources For Smart NIC and DPU Hosts"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/cluster-network-operator#1721

Test revert, something has changed with disruption, we want to see if this is involved.

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by bertinatto** [comment]
It seems like this reverted solved the problem. Doing another run to have more data for tomorrow.

/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by dgoodwin** [comment]
I fear this isn't it, our first batch of 10 jobs, only 8 installed, disruption for kube-api was 2 0 6 2 2 7 6 8 for an average of 4.1.
Second batch again only 8 installed, disruption for kube-api was 5 4 10 8 5 5 7 9 for an average of 6.6.

Looking at https://grafana-loki.ci.openshift.org/d/ISnBj4LVk/disruption?from=now-30d&to=now&var-platform=azure&var-percentile=P50&var-backend=kube-api-new-connections&var-releases=4.14&var-from_releases=4.14&var-networks=ovn&var-topologies=ha&var-architectures=amd64&var-min_job_runs=10&orgId=1 our average yesterday was 5.7, so I fear this is probably not our regression. (if there even is a regression)

/close

**Pull request closed without merging**
