### PR TITLE
SDN-4546: Configure CNO as per new API changes for join and transit switch subnet

### PR DESCRIPTION
**Pull request by arghosh93**
This PR is to backport https://github.com/openshift/cluster-network-operator/pull/2318 into release-4.15 branch.

API changes into release-4.15[1] has not merged yet. Hence currently pointing openshift/api to unmerged PR.

Fixed couple of merged conflicts occurred during cherry-pick.

[1] - https://github.com/openshift/api/pull/1872

### CODE REVIEW

**Comment by anuragthehatter** [comment]
QE regression looks good

/label qe-approved

**Comment by arghosh93** [comment]
I can see that API changes have been backported to release-4.15 via https://github.com/openshift/api/pull/1872.

Still keeping this PR on hold due to masquerade subnet related implementation not being backported to release-4.15 yet. Ref: https://github.com/openshift/cluster-network-operator/pull/2375

cc: @bpickard22

**Pull request closed without merging**
