### PR TITLE
OCPBUGS-5842: Use pods oc vs host

### PR DESCRIPTION
**Pull request by mccv1r0**
Use pods oc vs host

Signed-off-by: Michael Cambria <mcambria@redhat.com>

### CODE REVIEW

**Comment by mccv1r0** [comment]
They yaml involved doesn't even exist in OVN.  It also only applies to `{{- if .SDNPlatformAzure}}`

Any test failures on OVN or !Azure are most likely not related to this PR.

**Comment by mccv1r0** [comment]
Needs a test override for e2e-network-migration due to https://issues.redhat.com/browse/SDN-3681 ?? 

The change here is specific to Azure using SDN for CNI: https://github.com/openshift/cluster-network-operator/pull/1681#issuecomment-1397254550

**Comment by sdodson** [comment]
@mccv1r0 looks like all required tests passed, should we remove the hold?

**Comment by mccv1r0** [comment]
> @mccv1r0 looks like all required tests passed, should we remove the hold?

A bot added the hold, don't know why.  Remove it

**Comment by stbenjam** [comment]
Looks like https://github.com/openshift/sdn/pull/495 needed to land first, can you make it all one PR and use the payload command above to test?

**Pull request merged**
