### PR TITLE
[release-4.11] OCPBUGS-3490: OVN-Kubernetes: Prefer oldest nodes

### PR DESCRIPTION
**Pull request by kyrtapz**
This cherry picks the improvements to ovn-k startup from https://github.com/openshift/cluster-network-operator/pull/1579

/cc @martinkennelly @dcbw

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest
 Job e2e-hypershift is failing with "failed to get version for release image". Looks like registry issue.

**Comment by martinkennelly** [comment]
/retest
:(

**Comment by kyrtapz** [comment]
HyperShift failure doesn't look related, OVN-K Master is [up](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1641/pull-ci-openshift-cluster-network-operator-release-4.11-e2e-hypershift/1600805714819813376/artifacts/e2e-hypershift/dump/artifacts/namespaces/clusters-c067a3aff7106049df2d/core/pods/ovnkube-master-0.yaml) and [running](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1641/pull-ci-openshift-cluster-network-operator-release-4.11-e2e-hypershift/1600805714819813376/artifacts/e2e-hypershift/dump/artifacts/namespaces/clusters-c067a3aff7106049df2d/core/pods/logs/ovnkube-master-0-ovnkube-master.log)

**Pull request merged**
