### PR TITLE
OCPBUGS-34612,OCPBUGS-34660,OCPBUGS-34663: Live migration backports

### PR DESCRIPTION
**Pull request by martinkennelly**
Main metrics PR: https://github.com/openshift/cluster-network-operator/pull/2388
Main validation PR: https://github.com/openshift/cluster-network-operator/pull/2344
Main align subnet PR: https://github.com/openshift/cluster-network-operator/pull/2367

All commits are clean cherry-picks.

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
pre-merge testing this PR. all testing LG
/label qe-approve

**Comment by martinkennelly** [comment]
/test e2e-vsphere-ovn-dualstack-primaryv6

Unrelated image pull issue

**Pull request merged**
