### PR TITLE
Whereabouts IPAM CNI, add entrypoint logging methods. Update CRDs to v1

### PR DESCRIPTION
**Pull request by dougbtv**
The error() method when called would produce no output and an error from /bin/sh otherwise.

### CODE REVIEW

**Review by danielmellado — COMMENTED** [review]
Please! Let's get this in xD

**Comment by dougbtv** [comment]
/retitle Whereabouts IPAM CNI, add entrypoint logging methods. Update CRDs to v1

**Comment by rcarrillocruz** [comment]
Looks like some changes are needed on the CRD:

level=error msg=Cluster operator network Degraded is True with ApplyOperatorConfig: Error while updating operator configuration: could not apply (apiextensions.k8s.io/v1, Kind=CustomResourceDefinition) /network-attachment-definitions.k8s.cni.cncf.io: could not create (apiextensions.k8s.io/v1, Kind=CustomResourceDefinition) /network-attachment-definitions.k8s.cni.cncf.io: CustomResourceDefinition.apiextensions.k8s.io "network-attachment-definitions.k8s.cni.cncf.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required

**Pull request closed without merging**
