### PR TITLE
OCPBUGS-27222,NP-874: Bump openshift API

### PR DESCRIPTION
**Pull request by kyrtapz**
Includes moving the live migration to default.
Additionally it pulls the CNCC change, cc: @dulek 

Commands ran:
```
go get github.com/openshift/api@master
go mod tidy && go mod vendor
./hack/update-codegen.sh
```

### CODE REVIEW

**Comment by dulek** [comment]
/lgtm

Wow, thank you! Should I retitle this to apply OCPBUGS-27222?

**Comment by kyrtapz** [comment]
/hold
I want to make sure it works on a cluster built with the PR
@martinkennelly ptal

**Comment by martinkennelly** [comment]
/unhold

Tested. It works as expected.

**Comment by kyrtapz** [comment]
Windows job passed the test but failed during de-provisioning: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-network-operator/2246/pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-windows/1753338385054830592

/retest-required

**Pull request merged**
