### PR TITLE
Remove LB management

### PR DESCRIPTION
**Pull request by MaysaMacedo**
Kuryr now handles the default Service named kubernetes, consequently
we should remove the management from CNO.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/hold
Need to check impact during upgrades.

**Comment by dulek** [comment]
-452, I bet CNO folks will love this. :D

**Comment by MaysaMacedo** [comment]
Let's only merge it, once https://github.com/openshift/kuryr-kubernetes/pull/473 is merged.

**Comment by MaysaMacedo** [comment]
The vendoring part can probably be removed in another pr

**Review by gryf — APPROVED** [review]
/lgtm

**Pull request merged**
