### PR TITLE
Removing old kuryr-kubernetes CRDs

### PR DESCRIPTION
**Pull request by scavnicka**
When moving from annotation to CRD, old CRDs was left to allow user to upgrade from 4.5 to 4.6 version. Now we are going to upgrade to ocp 4.8, so everyone should already use CRD instead of annotations and we can remove the old CRDs, which was used when we have worked with annotations.

### CODE REVIEW

**Comment by dulek** [comment]
/lgtm

Seems good to me, we should probably test this a bit on a live setup.

**Comment by dulek** [comment]
Seems like you need to update the tests too: https://github.com/openshift/cluster-network-operator/blob/master/pkg/network/kuryr_test.go#L70. I'd just update it to check for all the CRDs that still exist.

**Comment by MaysaMacedo** [comment]
/hold

Holding it from merging, just so that we can test it.

**Comment by MaysaMacedo** [comment]
Could you squash all the commits into the first commit  "Removing old kuryr-kubernetes CRDs"?

**Comment by MaysaMacedo** [comment]
It worked fine.

**Comment by danwinship** [comment]
"Needs bugzilla/valid-bug label." (ie, needs a bz now if you want it to merge in 4.8)

**Comment by dulek** [comment]
/hold

I'm not sure if this is worth a BZ.

**Comment by dulek** [comment]
/hold cancel

Well, we can merge it without the BZ now. ;)

**Pull request merged**
