### PR TITLE
Bug 1907644: fix up non-critical / Progressing status handling

### PR DESCRIPTION
**Pull request by danwinship**
Fixes three problems:

1. network-check-source cannot be scheduled to masters, but it was not marked as "non-critical", so if a cluster install fails before the worker nodes are created, you would see:

    `level=error msg=Cluster operator network Degraded is True with RolloutHung: Deployment "openshift-network-diagnostics/network-check-source" rollout is not making progress - last change 2020-12-10T14:03:43Z `

    in the logs

2. We didn't have a special-case "waiting for other operators" message for non-critical Deployments (as opposed to for non-critical DaemonSets) so even after fixing the above, you'd still see CNO as Progressing with

    `Deployment "openshift-network-diagnostics/network-check-source" is not available (awaiting 1 nodes)`

    which makes it sound like _we're_ doing something wrong, as opposed to merely suffering because of someone else's bug.

3. The DaemonSet "waiting for other operators" special case only worked for pods that couldn't be scheduled on masters; in the case of network-metrics-daemon and network-check-target, they _can_ be scheduled to masters but still don't actually _start_ until late in the install because they're waiting for the cert operator. So this needed some tweaking.

### CODE REVIEW

**Comment by danwinship** [comment]
from e2e-gcp:

```
- lastTransitionTime: "2020-12-11T14:24:32Z"
  message: |-
    DaemonSet "openshift-multus/multus" is not available (awaiting 3 nodes)
    DaemonSet "openshift-multus/network-metrics-daemon" is waiting for other operators to become ready
    DaemonSet "openshift-multus/multus-admission-controller" is waiting for other operators to become ready
    DaemonSet "openshift-sdn/sdn-controller" is not available (awaiting 3 nodes)
    DaemonSet "openshift-sdn/ovs" is not available (awaiting 3 nodes)
    DaemonSet "openshift-sdn/sdn" is not available (awaiting 3 nodes)
    DaemonSet "openshift-network-diagnostics/network-check-target" is not available (awaiting 3 nodes)
    Deployment "openshift-network-diagnostics/network-check-source" is waiting for other operators to become ready
  reason: Deploying
```

...

```
- lastTransitionTime: "2020-12-11T14:24:32Z"
  message: |-
    DaemonSet "openshift-multus/network-metrics-daemon" is waiting for other operators to become ready
    DaemonSet "openshift-multus/multus-admission-controller" is waiting for other operators to become ready
    Deployment "openshift-network-diagnostics/network-check-source" is waiting for other operators to become ready
  reason: Deploying
  status: "True"
  type: Progressing
- lastTransitionTime: "2020-12-11T14:26:09Z"
  status: "True"
  type: Available
```

...

```
- lastTransitionTime: "2020-12-11T14:24:32Z"
  message: |-
    DaemonSet "openshift-multus/network-metrics-daemon" is not available (awaiting 3 nodes)
    DaemonSet "openshift-multus/multus-admission-controller" is not available (awaiting 3 nodes)
    Deployment "openshift-network-diagnostics/network-check-source" is not available (awaiting 1 nodes)
  reason: Deploying
  status: "True"
  type: Progressing
```

...

```
- lastTransitionTime: "2020-12-11T14:32:34Z"
  status: "False"
  type: Progressing
```

**Comment by squeed** [comment]
Seems reasonable. I have a refactor of the statusmanager that didn't make 4.7 that will, hopefully, make it easier for control loops to report this explicitly, rather than piecing it out.

/lgtm

**Comment by danwinship** [comment]
> [`docs: add some basic info about CNO's operands`](https://github.com/openshift/cluster-network-operator/pull/911/commits/aea8f1375174dae1b679a38cf642dc8b653fd2c8)

@rcarrillocruz needs a new `/lgtm` for the added commit

**Pull request merged**
