### PR TITLE
Bug 1942604: Allow-from-router network policy support for ovn-kubernetes

### PR DESCRIPTION
**Pull request by abhat**
This PR cherry-picks commits needed for supporting allow-from-router feature to apply network policy to router endpoints when the endpoint publishing strategy is `HostNetwork`.

### CODE REVIEW

**Comment by asood-rh** [comment]
@abhat Tested on AWS cluster.

allow-from-router works with old label network.openshift.io/policy-group: ingress but does not work with new label **policy-group.network.openshift.io/ingress: ""**.

allow-from-hostnetwork works fine on the build.

Client Version: 4.7.0
Server Version: 4.6.0-0.ci.test-2021-07-09-190146-ci-ln-wm7tri2-latest
Kubernetes Version: v1.19.2-1083+4c3480dcd4299c-dirty

**Comment by asood-rh** [comment]
All three policies - allow-from-router (old and new label) and allow-from-hostnetwork work fine on a cluster on vSphere (oc get --namespace openshift-ingress-operator ingresscontrollers/default --output jsonpath='{.status.endpointPublishingStrategy.type}'
HostNetwork)

oc version
Client Version: 4.7.0
Server Version: 4.6.0-0.ci.test-2021-07-09-190146-ci-ln-wm7tri2-latest
Kubernetes Version: v1.19.2-1083+4c3480dcd4299c-dirty

**Comment by abhat** [comment]
This PR depends on openshift/ovn-kubernetes#603 to land first. We need to cherry-pick both the PRs for the next 4.6.z.

**Comment by abhat** [comment]
The metal-ipi-ovn-ipv6 job is failing because of a bug that is specifically exposed in a more pronounced way in case of 4.6.
/hold

**Pull request merged**
