### PR TITLE
OCPBUGS-24693: HyperShift, network-node-identity: Check the deployment in the management cluster

### PR DESCRIPTION
**Pull request by kyrtapz**
In HyperShift the network-node-identity deployment is located in the management cluster. Use the appropriate client to retrieve it.

### CODE REVIEW

**Comment by kyrtapz** [comment]
I have manually verified that the webhook is properly applied in the hosted cluster and is enforcing the checks on pod and node updates.

**Comment by jcaamano** [comment]
/override ci/prow/e2e-aws-sdn-network-migration-rollback 
/override ci/prow/e2e-aws-sdn-network-reverse-migration

These failures do not look like they are related to the cnages on this PR. @kyrtapz registered a bug to track it:
https://issues.redhat.com/browse/OCPBUGS-25863

**Pull request merged**
