### PR TITLE
OCPBUGS-1083: Add/increase pending time for flaky alerts 

### PR DESCRIPTION
**Pull request by npinaeva**
while we are figuring out how to improve the expressions

Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>

### CODE REVIEW

**Comment by npinaeva** [comment]
failed again, but that is not us 
```
{  1 events happened too frequently

event happened 23 times, something is wrong: ns/openshift-oauth-apiserver pod/apiserver-648b49c986-ddjzh node/ip-10-0-241-77.us-east-2.compute.internal - reason/ProbeError Readiness probe error: Get "https://10.128.0.38:8443/readyz": dial tcp 10.128.0.38:8443: connect: connection refused
body: 
}
```

**Comment by jluhrsen** [comment]
> failed again, but that is not us
> 
> ```
> {  1 events happened too frequently
> 
> event happened 23 times, something is wrong: ns/openshift-oauth-apiserver pod/apiserver-648b49c986-ddjzh node/ip-10-0-241-77.us-east-2.compute.internal - reason/ProbeError Readiness probe error: Get "https://10.128.0.38:8443/readyz": dial tcp 10.128.0.38:8443: connect: connection refused
> body: 
> }
> ```

yeah, ignore this one for what this PR is working on.

**Comment by npinaeva** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1569/pull-ci-openshift-cluster-network-operator-master-e2e-aws-ovn-serial/1575392358369857536
first pass

**Comment by npinaeva** [comment]
ovnkube-pods have unpredictable behaviour when the 4th node is added: number of db members can be 3 or 4 for almost the whole 4th node lifetime.
Since we have https://github.com/openshift/cluster-network-operator/pull/1560 already up, that should fix this problem, we can try to retest after it merges
Or I need to increase pending time to more than 30 min, which I I am hesitant to do now

**Comment by npinaeva** [comment]
This fix is taking too long, revert newly added alerts https://github.com/openshift/cluster-network-operator/pull/1578

**Pull request closed without merging**
