### PR TITLE
Bug 2035459: modify cluster-network-features for OpenshiftSDN

### PR DESCRIPTION
**Pull request by mariomac**
According to the recent comment of Dan Winship in a recently merged
PR: https://github.com/openshift/cluster-network-operator/pull/1204#issuecomment-990201372

> openshift-sdn also implements both egress rules and ipBlock exceptions.

This PR updates the reported capabilities for OpenshiftSDN so the Console
will accordingly show the proper sections in the Network Policy forms.

### CODE REVIEW

**Comment by jotak** [comment]
@martinkennelly looks like the failing tests are unrelated to this change, right? Are they frequently failing randomly? Is it possible to bypass them?

**Comment by martinkennelly** [comment]
> @martinkennelly looks like the failing tests are unrelated to this change, right? Are they frequently failing randomly? Is it possible to bypass them?

Theres an issue with dual stack job. Ask Tim/aniket for an override if that job is blocking you.
I'm away from office.

**Comment by mariomac** [comment]
@trozet @abhat this is the bug that the tests are preventing us to complete (we double-checked that the failing tests are unrelated to our small change): https://bugzilla.redhat.com/show_bug.cgi?id=2035459

¿Would it be possible to override tests? Thanks

**Pull request merged**
