### PR TITLE
OCPBUGS-10765: Revert "Revert "OCPBUGS-10765: Remove oldest ovn acl log files when f…

### PR DESCRIPTION
**Pull request by jluhrsen**
…ile limit exceeded""

This reverts commit ef2c381d4e18aa5edc2f69c3f37f08b3f3021fc0.

- fixes unbound variable log_dir, replaces with LOGDIR which is properly initialized

### CODE REVIEW

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/OCPBUGS-10765

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-ovn-windows

```
 --- FAIL: TestWMCO (3161.38s)
    --- FAIL: TestWMCO/create (3160.94s)
        --- FAIL: TestWMCO/create/Creation (3160.69s)
            --- PASS: TestWMCO/create/Creation/Machine_controller (641.41s)
            --- FAIL: TestWMCO/create/Creation/ConfigMap_controller (2519.03s)
                --- FAIL: TestWMCO/create/Creation/ConfigMap_controller/VM_is_configured_by_ConfigMap_controller (2100.14s)
FAIL
```

not a networking thing.

**Pull request merged**
