### PR TITLE
Revert "IC & openshift + hypershift"

### PR DESCRIPTION
**Pull request by sjenning**
Reverts openshift/cluster-network-operator#1874

Took out hypershift CI on upgrade and caused CI release rejection on https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-08-09-113535

https://testgrid.k8s.io/redhat-hypershift#4.14-aws-ovn

`network` ClusterOperator stuck Progressing because the `ovnkube-control-plane` deployment fails to upgrade.

The new `ovnkube-control-plane` deployment does not set `maxSurge: 0` and thus fails to rollout on upgrade on a test cluster with 3 nodes due to anti-affinity rules.

This got past CI because it works when upgrading from a release that does not already have the `ovnkube-control-plane` deployment, but it does not work when the initial release has the deployment.

### CODE REVIEW

**Comment by sjenning** [comment]
/override ci/prow/e2e-hypershift-ovn

This will not pass hypershift CI upgrade test because the initial release contains the deployment with the issue

**Comment by trozet** [comment]
/hold

as we think #1944 is a better option as long as it works correctly

**Comment by davidvossel** [comment]
@trozet This issue is not resolved for Hypershift still, The Hypershift/KubeVirt platform has been broken since IC was enabled. 

https://issues.redhat.com/browse/OCPBUGS-17666

Can we reverting IC until this is resolved

**Comment by tssurya** [comment]
@davidvossel : please give us time to look into this, @flavio-fernandes and @jcaamano are looking into this, let's not jump to reverting yet.

**Pull request closed without merging**
