### PR TITLE
Set the host-network-namespace parameter for ovn-kubernetes

### PR DESCRIPTION
**Pull request by abhat**
This commit puts the host-network-namespace setting in the config
map that ovn-kubernetes mounts to read in the Kubernetes config.

Signed-off-by: Aniket Bhat <anbhat@redhat.com>

### CODE REVIEW

**Comment by abhat** [comment]
Wait on the github.com/ovn-org/ovn-kubernetes/pull/2093 to merge downstream.

**Comment by squeed** [comment]
Seems reasonable, but this is still pending upstream and downstream merges, right?

**Comment by abhat** [comment]
we don't need to gate it on upstream PR merging. Worst case the downstream ovn-k continues to ignore the config map.

**Comment by abhat** [comment]
/hold

Looks like the config file parsing is failing because the downstream PR hasn't landed.

**Comment by danwinship** [comment]
the files need to be renamed to be more specific if they're going to be in a non-host-network-namespace-specific directory (eg, `openshift-sdn/ns.yaml` sounds like it's the openshift-sdn namespace, not the openshift-host-network namespace)

**Comment by abhat** [comment]
@danwinship renamed the files PTAL.

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by abhat** [comment]
The downstream PR has merged. Removing the do-not-merge label.

/hold cancel

**Comment by squeed** [comment]
Manually adding valid-bug; this PR was filed ages ago and got caught in CI heck.

**Comment by squeed** [comment]
Great, it decided to retest everything (probably because something else merged in this repo)

**Pull request merged**
