### PR TITLE
Cno 4.13 kubernetes 1.26

### PR DESCRIPTION
**Pull request by jluhrsen**
JIRA: https://issues.redhat.com/browse/SDN-3636

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold

this is still broken because of this error:
```

❯ make build
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/cluster-network-operator/pkg/version.versionFromGit="v0.0.0-unknown-f79efd8a1" -X github.com/openshift/cluster-network-operator/pkg/version.commitFromGit="f79efd8a1" -X github.com/openshift/cluster-network-operator/pkg/version.gitTreeState="clean" -X github.com/openshift/cluster-network-operator/pkg/version.buildDate="2023-02-09T21:35:28Z" " github.com/openshift/cluster-network-operator/cmd/cluster-network-check-endpoints
go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/cluster-network-operator/pkg/version.versionFromGit="v0.0.0-unknown-f79efd8a1" -X github.com/openshift/cluster-network-operator/pkg/version.commitFromGit="f79efd8a1" -X github.com/openshift/cluster-network-operator/pkg/version.gitTreeState="clean" -X github.com/openshift/cluster-network-operator/pkg/version.buildDate="2023-02-09T21:35:28Z" " github.com/openshift/cluster-network-operator/cmd/cluster-network-check-target
go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/cluster-network-operator/pkg/version.versionFromGit="v0.0.0-unknown-f79efd8a1" -X github.com/openshift/cluster-network-operator/pkg/version.commitFromGit="f79efd8a1" -X github.com/openshift/cluster-network-operator/pkg/version.gitTreeState="clean" -X github.com/openshift/cluster-network-operator/pkg/version.buildDate="2023-02-09T21:35:28Z" " github.com/openshift/cluster-network-operator/cmd/cluster-network-operator
# sigs.k8s.io/cluster-api/api/v1beta1
vendor/sigs.k8s.io/cluster-api/api/v1beta1/machineset_types.go:184:83: not enough arguments in call to metav1validation.ValidateLabelSelector
        have (*"k8s.io/apimachinery/pkg/apis/meta/v1".LabelSelector, *field.Path)
        want (*"k8s.io/apimachinery/pkg/apis/meta/v1".LabelSelector, validation.LabelSelectorValidationOptions, *field.Path)
make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 2

```

I believe this cannot be resolved until there is a new version of k8s.io/cluster-api to update to. The main branch
does now use the new signature call to ValidateLabelSelector(), but the most recent tag available (v1.3.3) is still using the old version.

**Comment by jluhrsen** [comment]
build jobs are gonna fail until the build env is updated to use golang 1.19. I have a PR [here](https://issues.redhat.com/browse/SDN-3636) to do that.

**Comment by dcbw** [comment]
Assuming it passes CI...

/approve
/lgtm

**Comment by dcbw** [comment]
/test e2e-gcp-ovn

error: failed to push image registry.build04.ci.openshift.org/ci-op-p6sh1rmc/release:latest: uploading the source layer sha256:7b796951b33c87c15d3c10c0912c2ae51ad3a6cfb394f844f21efce1b295ca3d failed: unable to upload layer sha256:7b796951b33c87c15d3c10c0912c2ae51ad3a6cfb394f844f21efce1b295ca3d to destination repository: received unexpected HTTP status: 504 Gateway Timeout

**Pull request merged**
