### PR TITLE
Revert "Revert "openshift-sdn: log ovs and sdn to the system journal""

### PR DESCRIPTION
**Pull request by squeed**
Brings #161 back

### CODE REVIEW

**Comment by squeed** [comment]
for soak time:
/hold

**Comment by squeed** [comment]
This basically brings our logging back to what we had in 3.9 / uncontainerized 3.10.

**Comment by squeed** [comment]
@smarterclayton observes that -V=4 kube-proxy logging has caused availability / io starvation in the past, so perhaps this isn't actually safe.

My instinct would be that I'd rather have preserved logs at a lower verbosity over container-contstrained high verbosity. We gave ourselves the ability to enable per-node debugging with a sysconfig.

**Comment by smarterclayton** [comment]
I liked most of the logs that were written - especially the SDN health check failure.  That was extremely valuable.  On a 20k service cluster, I think per service or per endpoint stuff can be risky.  Do we have any other "per service" output in ovs that we'd have to mask?

**Comment by danwinship** [comment]
> Do we have any other "per service" output in ovs that we'd have to mask?

No, kube-proxy output makes up the bulk of sdn logging these days. (It's the sdn container, not the ovs container; the ovs container only logs stuff per-pod.)

When you say "mask", what do you mean exactly? Carrying patches to change the log level in the vendored kube-proxy code, or just grepping out high-frequency messages before piping to `logger`?


The kube-proxy logging is sometimes useful for debugging issues (eg, figuring out retroactively where 172.30.0.1 was pointing at a given time) although it's also incomplete in some ways and redundant in others. We should probably revisit exactly what gets logged anyway.

Although too late for 4.1, it wouldn't be too hard to make it possible to run the proxy and the sdn core as separate containers again (with separate logging), although that might be a lose in terms of memory usage.

**Comment by squeed** [comment]
FWIW, essentially all of the loud messages come from the hybrid proxy wrapper, so we wouldn't have to carry any patches to change them.

**Comment by squeed** [comment]
So, I'd like to know how much of the concern is raw disk IO vs. specific journald concerns. Is logging to journald that much more expensive than crio logs? (It could be - I've not heard great things, but I've never done any sort of benchmarking). 

As @danwinship mentioned, we've found it quite useful to indicate exactly the state of the service network at a point in time - these sorts of point-in-time RCA explorations are not uncommon.

**Comment by danwinship** [comment]
> FWIW, essentially all of the loud messages come from the hybrid proxy wrapper, so we wouldn't have to carry any patches to change them.

The actual messages are logged by the upstream userspace proxy code (so they're *because of* the hybrid proxy wrapper, but not *from* the hybrid proxy wrapper).

**Comment by smarterclayton** [comment]
We should be able to set log level per filename grep pattern with `-vmodule` to mask the worst offenders.

**Comment by smarterclayton** [comment]
journal still has bottlenecks deep that can cause one process to block / limit another.  so hygiene for now is those who must log to journal must only do so with known bounded quantities

**Pull request closed without merging**
