### PR TITLE
[release-4.14] OCPBUGS-22787,OCPBUGS-22788,OCPBUGS-22789: ovnkube: container scripts cleanup

### PR DESCRIPTION
**Pull request by dcbw**
Put common scripts into a bash script library and source that library from the ovnkube-node containers.

### CODE REVIEW

**Comment by dcbw** [comment]
/retest

https://github.com/openshift/release/pull/45159

**Comment by dcbw** [comment]
/test e2e-hypershift-ovn

https://github.com/openshift/release/pull/45961

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/OCPBUGS-20274

**Pull request merged**
