### PR TITLE
ovnkube: better logging for upgrades/downgrades

### PR DESCRIPTION
**Pull request by dcbw**
@squeed @trozet

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
lease issues and other infrastructure related flakes

**Comment by dcbw** [comment]
Azure seems to consistently have issues with:

```
level=fatal msg=failed to fetch Master Machines: failed to load asset "Install Config": [platform.azure.region: Internal error: failed to retrieve available regions: failed to list locations: subscriptions.Client#ListLocations: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed.", compute[0].platform.azure.type: Invalid value: "Standard_D4s_v3": not found in region centralus]
```

**Comment by dcbw** [comment]
gcp is failing because it's not yet using https://github.com/openshift/origin/pull/25962

**Review by trozet — COMMENTED** [review]
@dcbw why dont I see any of these messages in the upgrade job CNO log?
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1023/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-upgrade/1371531426440155136/artifacts/e2e-gcp-ovn-upgrade/gather-extra/artifacts/pods/openshift-network-operator_network-operator-cf9875c64-4wwjd_network-operator.log

**Comment by dcbw** [comment]
> @dcbw why dont I see any of these messages in the upgrade job CNO log?
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1023/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-upgrade/1371531426440155136/artifacts/e2e-gcp-ovn-upgrade/gather-extra/artifacts/pods/openshift-network-operator_network-operator-cf9875c64-4wwjd_network-operator.log

@trozet you don't see any because upgrade uses the same image for hte upgrade as install. So the versions actually never change:

`Installing from release registry.build01.ci.openshift.org/ci-op-1z4bmn9p/release@sha256:07987cd8776b60cbdcf949046331342cf24e01169f5cef4ba009dc6e48658e29`

`openshift-tests run-upgrade all --to-image registry.build01.ci.openshift.org/ci-op-1z4bmn9p/release@sha256:07987cd8776b60cbdcf949046331342cf24e01169f5cef4ba009dc6e48658e29 --options '' --provider '{"type":"gce","region":"us-east1","multizone": true,"multimaster":true,"projectid":"openshift-gce-devel-ci"}' -o /logs/artifacts/e2e.log --junit-dir /logs/artifacts/junit`

and thus we always hit this block in `shouldUpdateOVNK()` but never get past to our logging:

```
	// shortcut - we're all rolled out.
	// Return true so that we reconcile any changes that somehow could have happened.
	if nodeVersion == releaseVersion && masterVersion == releaseVersion {
		return true, true
	}
```

**Comment by dcbw** [comment]
@trozet pushed a logging change to test that theory out...

**Comment by dcbw** [comment]
@trozet Confirmed that our upgrade jobs never actually run the upgrade code, because they do not change the cluster release version. So these paths never actually get exercised because our upgrade jobs suck.

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6 
metal operators do not yet specify resource requests, which is a new requirement as of yesterday

**Comment by dcbw** [comment]
/retest
gcp capacity issues

**Pull request merged**
