### PR TITLE
Bug 1743587: Adding cni-version to multus daemonset yaml

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
A backport of PR [291](https://github.com/openshift/cluster-network-operator/pull/291)

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
/retitle Backport 1743587: Adding cni-version to multus daemonset yaml

**Comment by alexanderConstantinescu** [comment]
/retitle Bug 1743587: Adding cni-version to multus daemonset yaml

**Comment by eparis** [comment]
This just requires lgtm/approval from the engineering team.  Does this need to merge with https://github.com/openshift/multus-cni/pull/20 ? If one merged without the other will something break?  (and if yes, how did they both pass ci?)

**Comment by danwinship** [comment]
> Does this need to merge with [openshift/multus-cni#20](https://github.com/openshift/multus-cni/pull/20) ? If one merged without the other will something break?

Both are needed, but they don't need to merge in sync; if the multus PR merges first, it will just add a command-line option that isn't getting used. If this merges first then the multus setup container will log a warning about an unrecognized command-line option but will otherwise behave exactly like it did before this PR.

**Comment by alexanderConstantinescu** [comment]
FYI: [multus PR](https://github.com/openshift/multus-cni/pull/20) has been approved, so this should be "good to go".

**Pull request merged**
