### PR TITLE
[release-4.10] OCPBUGS-1538: Make northd probe interval default to 10 seconds

### PR DESCRIPTION
**Pull request by tssurya**
/cc @trozet 
brings in https://github.com/openshift/cluster-network-operator/pull/1386/commits/eebce7172b9fc236a454809dc1768fcf7b3703fd and https://github.com/openshift/cluster-network-operator/pull/1494/files (which is the right fix)

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

thanks @tssurya !

**Comment by tssurya** [comment]
@trozet : needs the risk assessed label

**Comment by tssurya** [comment]
@anuragthehatter : PTAL

**Pull request merged**
