### PR TITLE
Bug 1912820: competing connectivitycheckcontrollers cause pod restarts during upgrades

### PR DESCRIPTION
**Pull request by sanchezl**
- pickup library-go#987
- remove podnetworkconnectivitycheck from CVO control

### CODE REVIEW

**Comment by danwinship** [comment]
> `[proof: pickup openshift/library-go#987]`

I think people generally try to avoid using strings that will trigger github's automatic linking-via-commit-message, since it tends to totally spam the linked PR/issue (eg, another message every time you push an updated version of the commit)

**Comment by danwinship** [comment]
lgtm
/hold
for the library-go change to actually merge

**Comment by deads2k** [comment]
> * remove podnetworkconnectivitycheck from CVO control

For the future, using the CVO prevents any conditional creation, list/watch reaction speed, conditional removal, selective mutation, coordination between operators.  It is basically always better to avoid the CVO.

/lgtm

**Pull request merged**
