### PR TITLE
Allow updates to pods

### PR DESCRIPTION
**Pull request by bn222**
https://issues.redhat.com/browse/NHE-443

https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/cni/cni_dpu.go#L70

### CODE REVIEW

**Comment by zshi-redhat** [comment]
/lgtm
cc @jcaamano

**Comment by zshi-redhat** [comment]
In dpu-host mode, ovnkube-node on the host needs to update pod annotation to inform the ovnkube-node on the dpu about which interface to plug to OVS.

**Comment by bn222** [comment]
> In dpu-host mode, ovnkube-node on the host needs to update pod annotation to inform the ovnkube-node on the dpu about which interface to plug to OVS.

This is correct. The important code for this can be found here: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/cni/cni_dpu.go#L70

**Pull request merged**
