### PR TITLE
OVN - fix cluster role binding

### PR DESCRIPTION
**Pull request by pecameron**
Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@dcbw @danwinship PTAL

**Comment by squeed** [comment]
omg
/lgtm

**Comment by dcbw** [comment]
/hold 

hang on a sec, openshift-sdn doesn't do this, so it may not actually be required...

**Comment by pecameron** [comment]
@dcbw @squeed PTAL

**Comment by pecameron** [comment]
Some changes dcbw suggested.
@dcbw @squeed PTAL

**Pull request merged**
