### PR TITLE
add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by guillaumerose**
This is matches openshift/enhancements#414 and doesn't change existing behavior

### CODE REVIEW

**Comment by deads2k** [comment]
This matches the name in https://github.com/openshift/enhancements/blob/master/enhancements/update/cluster-profiles.md#proposal .

/lgtm

/assign @danwinship 
for approval ack

**Comment by squeed** [comment]
/override ci/prow/e2e-aws-sdn-multi
(is broken, bz 1890130)

**Pull request merged**
