### PR TITLE
Vendor: pull in hypershift

### PR DESCRIPTION
**Pull request by squeed**
This wound up being a total mess. Oof.

/cc @kyrtapz

### CODE REVIEW

**Comment by dulek** [comment]
/test e2e-openstack-kuryr

Looks good to me. Let's run Kuryr job to be sure.

**Comment by dulek** [comment]
Yep, Kuryr is happy.

**Comment by squeed** [comment]
@kyrtapz should we merge this PR directly or just include it as part of #1349?

**Comment by kyrtapz** [comment]
> @kyrtapz should we merge this PR directly or just include it as part of #1349?

I am ok with merging it directly, https://github.com/openshift/cluster-network-operator/pull/1345 needs hypershift api as well but is currently using the old version

**Comment by squeed** [comment]
CI failures are not meaningful - some random cleanup flakes. We can merge this
/override ci/prow/e2e-metal-ipi-ovn-ipv6
/override ci/prow/e2e-aws-sdn-multi

**Comment by squeed** [comment]
/override ci/prow/e2e-gcp
/override ci/prow/e2e-gcp-ovn
these jobs have been green many times. and now there are infra problems!?

**Pull request merged**
