### PR TITLE
[release-4.17] OCPBUGS-43714: Skip including default crypto policies to avoid authby issue

### PR DESCRIPTION
**Pull request by pperiyasamy**
Manual cherry-pick of https://github.com/openshift/cluster-network-operator/pull/2593, No conflicts.

### CODE REVIEW

**Comment by huiran0826** [comment]
/label qe-approved
/label cherry-pick-approved
```
sh-5.1# grep libreswan.config /etc/ipsec.conf 
# include /etc/crypto-policies/back-ends/libreswan.config
```

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Pull request merged**
