### PR TITLE
OCPBUGS-2362: Prefer oldest nodes, harden new alerts and revert setting new OVN-K alerts to info

### PR DESCRIPTION
**Pull request by martinkennelly**
All credit to nadia / dan w.
waiting on #1560 to merge and CI is consistently green after 10 retries including the ovn serial job.

### CODE REVIEW

**Comment by martinkennelly** [comment]
/test all

no alert failures seen

**Comment by martinkennelly** [comment]
/test all

no alert failures seen

**Comment by martinkennelly** [comment]
/test all

no alert failures seen

**Comment by martinkennelly** [comment]
None of the failures are occurring because of this PR. No alerts relating to this PR seen firing.

/retest

**Comment by martinkennelly** [comment]
@dcbw @tssurya @jluhrsen PTAL - You were on the original PR https://github.com/openshift/cluster-network-operator/pull/1560.
I tested this with cluster bot 10 times each with this PR for e2e-all, e2e-serial and e2e-upgrade from 4.11 and no issue.

**Comment by dcbw** [comment]
@martinkennelly I guess something changed:

```
 INFO[2022-10-26T20:59:41Z] Running `gofmt -s -l` on 120 file(s).
go vet  ./...
# github.com/openshift/cluster-network-operator/pkg/network
vet: pkg/network/ovn_kubernetes_test.go:2156:5: undeclared name: os 
```

Can you fix up?

**Comment by martinkennelly** [comment]
@dcbw Done
Added "os" import to commit [c0c317e](https://github.com/openshift/cluster-network-operator/pull/1579/commits/c0c317ebd560cd52ba7694ddc67fae0029683ab7)

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

v6 image registry pull errors that seem to be cropping up today in different places.

```
Oct 27 14:48:43.292739 worker-0.ostest.test.metalkube.org kubenswrapper[3392]: E1027 14:48:43.292645    3392 kuberuntime_manager.go:862] container &Container{Name:pause,Image:virthost.ostest.test.metalkube.org:5
000/localimages/local-test-image:e2e-28-registry-k8s-io-pause-3-8-aP7uYsw5XCmoDy5W,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Reque
sts:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-j896b,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},Livenes
sProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[],Drop:[ALL],},Privileged:nil,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:*false,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod pod-update-activedeadlineseconds-932d3668-8d81-40f0-81e2-b9ccd48d6db6_e2e-pods-7604(f90a9d09-9aa5-44c7-8caf-4f1a993b80b8): ErrImagePull: rpc error: code = Unknown desc = reading manifest e2e-28-registry-k8s-io-pause-3-8-aP7uYsw5XCmoDy5W in virthost.ostest.test.metalkube.org:5000/localimages/local-test-image: manifest unknown: manifest unknown
```

**Pull request merged**
