### PR TITLE
Bug 1834858: Kuryr: Remove old SG rules on upgrade

### PR DESCRIPTION
**Pull request by dulek**
In order to support updates in the SG rules added on Kuryr bootstrap we
need to make sure the security groups that got replaced by others are
removed. This commit, by maintaing list of "decommissioned" SG rules,
will make sure we delete them on upgrade.

### CODE REVIEW

**Comment by dulek** [comment]
/hold

This needs to wait for https://github.com/openshift/cluster-network-operator/pull/621 to be merged as it includes commits of it.

**Comment by sdodson** [comment]
/retitle Bug 1834858: Kuryr: Remove old SG rules on upgrade

**Comment by sdodson** [comment]
https://github.com/openshift/cluster-network-operator/pull/621 has merged
/hold cancel

**Pull request merged**
