### PR TITLE
Bug 1798887: Fixes Proxy ReadinessEndpoints Validation

### PR DESCRIPTION
**Pull request by danehans**
Previously, a TLS transport that includes a trusted CA bundle would only be created if the readiness endpoint had an https scheme. This PR updates `proxy.spec.readinessEndpoints` validation to use `proxy.spec.httpsProxy` if the `readinessEndpoints[x]` has an https scheme and `proxy.spec.httpsProxy` exists. Otherwise, `proxy.spec.httpProxy` will be used for all other `readinessEndpoints[]` validation.

### CODE REVIEW

**Comment by danwinship** [comment]
seems right, I think but I'll give other people a chance to look too...

**Comment by danehans** [comment]
`e2e-gcp` failed due to `ERROR: (gcloud.compute.instance-groups.list-instances) could not parse resource []`.

/test e2e-gcp

**Comment by danehans** [comment]
The same `ERROR: (gcloud.compute.instance-groups.list-instances) could not parse resource []` flake I'm seeing across tons of PRs.

/test e2e-gcp

**Comment by danehans** [comment]
The same `ERROR: (gcloud.compute.instance-groups.list-instances) could not parse resource []` flake I'm seeing across tons of PRs.

/test e2e-gcp

**Comment by squeed** [comment]
@danehans Do we need to get this in for 4.5?

/retest

**Comment by danehans** [comment]
@squeed I don't think this is a release blocker. IMO proxy readinessEndpoints are a "nice to have" feature that don't prevent core proxy functionality.

**Comment by danehans** [comment]
`error: unable to push registry.svc.ci.openshift.org/ci-op-ff3krsxr/stable: failed to retrieve blob sha256:20df32414cc569cfd82c50f12098364dd3c65c44f7ae1f415f00d354e8035a47: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"
`

/test e2e-metal-ipi

**Comment by danehans** [comment]
```
": "The checksum format is invalid", "url": "https://dl.k8s.io/v1.18.3/kubernetes-node-windows-amd64.tar.gz"}
                	            	
                	            	PLAY RECAP *********************************************************************
                	            	localhost                  : ok=18   changed=15   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
                	            	
```

/test e2e-windows-hybrid-network

**Comment by danehans** [comment]
`level=fatal msg="Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition"`

/test e2e-metal-ipi

**Comment by Miciah** [comment]
/cherry-pick release-4.3
per https://bugzilla.redhat.com/show_bug.cgi?id=1821956#c3.

**Pull request merged**
