### PR TITLE
Bug 1987046: Add pre-puller ds to reduce upgrade downtime

### PR DESCRIPTION
**Pull request by tssurya**
Manual Cherry-pick of https://github.com/openshift/cluster-network-operator/pull/1141 
Fixed conflicts due to https://github.com/openshift/cluster-network-operator/pull/1145

cc @vrutkovs

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retitle Bug 1987046: Add pre-puller ds to reduce upgrade downtime

**Comment by vrutkovs** [comment]
Started custom upgrade tasks:
* [test upgrade 4.7 4.8,https://github.com/openshift/cluster-network-operator/pull/1167 aws,ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1420467668246335488]
* [test upgrade 4.7 4.8,https://github.com/openshift/cluster-network-operator/pull/1167 gcp,ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1420467684545400832)

**Comment by vrutkovs** [comment]
Still seeing a lot of disruption:
>Jul 29 09:12:38.430: Frontends were unreachable during disruption for at least 26m6s of 1h21m25s (32%):
>Jul 29 09:12:38.430: Service was unreachable during disruption for at least 13m53s of 1h19m35s (17%):

**Comment by cgwalters** [comment]
Ultimately I think the best fix for this is that we do "pull through" caching in the registry instead of having each node pull each container.

**Comment by tssurya** [comment]
> Still seeing a lot of disruption:
> 
> > Jul 29 09:12:38.430: Frontends were unreachable during disruption for at least 26m6s of 1h21m25s (32%):
> > Jul 29 09:12:38.430: Service was unreachable during disruption for at least 13m53s of 1h19m35s (17%):

This solution of prepull is not perfect. The fact that there is disruption for 26 minutes cannot be solely due to OVN-K. It must be a combo of dependent components restarting during upgrades?

**Comment by tssurya** [comment]
> Ultimately I think the best fix for this is that we do "pull through" caching in the registry instead of having each node pull each container.

I don't know how that would look, but then again on prod's I don't know if the registries will be co-located? This PR doesn't do much alongside a run in CI (not sure how the CI setup looks like), but in larger envs, we expect more benefit.

**Comment by vrutkovs** [comment]
>It must be a combo of dependent components restarting during upgrades?

The only difference between [e2e-gcp-ovn-upgrade](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-gcp-ovn-upgrade) and [e2e-gcp-upgrade](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-gcp-upgrade) is OVN-K

**Comment by tssurya** [comment]
@vrutkovs : Should we get this fix in into 4.8? Or do we think we need a new fix to solve the service disruption issue and close this?

**Comment by vrutkovs** [comment]
I think this fix would be nice in 4.8, but clearly its not sufficient to fix all disruptions

**Pull request merged**
